$axure.loadCurrentPage({
  "url":"编辑车辆.html",
  "generationDate":new Date(1503556108113.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"page"],
  "page":{
    "packageId":"ee6fc5af969543aba51663ad760eea25",
    "type":"Axure:Page",
    "name":"编辑车辆",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1ee95fa39ecd405db948b93513dc483f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d96002076c7e487a803ce82dd616547c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/车辆页面/编辑页面_u8.png"}},
{
          "id":"c36ba96457234eb485ba3dc95123f4bb",
          "label":"完成",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":320,
              "y":20},
            "size":{
              "width":50,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30e633ab25d847518b93cee39d29e835",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":320,
                  "y":20},
                "size":{
                  "width":50,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 车辆页面",
                      "target":{
                        "targetType":"page",
                        "url":"车辆页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86b7faf57d644d6d83134692a61e8889",
          "label":"返回2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":20},
            "size":{
              "width":70,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ae5ec892a5d4ecdbe6d1be6540d6c8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":70,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 车辆页面",
                      "target":{
                        "targetType":"page",
                        "url":"车辆页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1ee95fa39ecd405db948b93513dc483f":{
      "scriptId":"u0"},
    "d96002076c7e487a803ce82dd616547c":{
      "scriptId":"u1"},
    "c36ba96457234eb485ba3dc95123f4bb":{
      "scriptId":"u2"},
    "30e633ab25d847518b93cee39d29e835":{
      "scriptId":"u3"},
    "86b7faf57d644d6d83134692a61e8889":{
      "scriptId":"u4"},
    "1ae5ec892a5d4ecdbe6d1be6540d6c8b":{
      "scriptId":"u5"}}});