$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1503556105069.04),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"page"],
  "page":{
    "packageId":"6e641b7310bd46119e7401e3a07c7ff3",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1<br> (If 值于 page 等于 &quot;100&quot;)",
            "isNewIfGroup":false,
            "condition":{
              "exprType":"binaryOp",
              "op":"==",
              "leftExpr":{
                "exprType":"fcall",
                "functionName":"GetGlobalVariableValue",
                "arguments":[{
                    "exprType":"globalVariableLiteral",
                    "variableName":"page"}]},
              "rightExpr":{
                "exprType":"stringLiteral",
                "value":"100",
                "stos":[]}},
            "actions":[{
                "action":"setPanelState",
                "description":"设置 首页 to 个人中心 显示隐藏",
                "panelsToStates":[{
                    "panelPath":["2fd825dc80094511a9eadab2ff51c181"],
                    "stateInfo":{
                      "setStateType":"diagram",
                      "stateNumber":2,
                      "stateValue":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]},
                      "loop":false,
                      "showWhenSet":true,
                      "options":{
                        "compress":false}}}]}]},
{
            "description":"用例 2<br> (Else If 值于 page 等于 &quot;111&quot;)",
            "isNewIfGroup":false,
            "condition":{
              "exprType":"binaryOp",
              "op":"==",
              "leftExpr":{
                "exprType":"fcall",
                "functionName":"GetGlobalVariableValue",
                "arguments":[{
                    "exprType":"globalVariableLiteral",
                    "variableName":"page"}]},
              "rightExpr":{
                "exprType":"stringLiteral",
                "value":"111",
                "stos":[]}},
            "actions":[{
                "action":"setPanelState",
                "description":"设置 首页 to 个人中心 显示隐藏",
                "panelsToStates":[{
                    "panelPath":["2fd825dc80094511a9eadab2ff51c181"],
                    "stateInfo":{
                      "setStateType":"diagram",
                      "stateNumber":2,
                      "stateValue":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]},
                      "loop":false,
                      "showWhenSet":true,
                      "options":{
                        "compress":false}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"2fd825dc80094511a9eadab2ff51c181",
          "label":"首页",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":794}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"4d92785020704556a5f0a6b8267c8cab",
              "label":"首页",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7784b0ed65424ebcb4df24cdd8aeb39c",
                  "label":"1",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":375,
                      "height":794}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"41856e76ec7f46ccadbe1c7227912a29",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":375,
                          "height":794}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/1_u1.png"}},
{
                  "id":"d9ffdfc373494d3496b90c0fab28a20c",
                  "label":"一键移车",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":119,
                      "y":220},
                    "size":{
                      "width":51,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0f8f05a290164f1bb71f0d5a05ae858e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":119,
                          "y":220},
                        "size":{
                          "width":51,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"已实名",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 一键移车—提交申请",
                              "target":{
                                "targetType":"page",
                                "url":"一键移车—提交申请.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f984c025a6854700b8a07f30867fd492",
                  "label":"驾驶人违反查询",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":369},
                    "size":{
                      "width":70,
                      "height":91},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4a1c38e616794754b9a37b07f1dbf0f5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":369},
                        "size":{
                          "width":70,
                          "height":91},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 驾驶人交通违法查询",
                              "target":{
                                "targetType":"page",
                                "url":"驾驶人交通违法查询.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"950aec15a75c49e29e30c599b8872a58",
                  "label":"路况地图",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":99.9999923706055,
                      "y":520},
                    "size":{
                      "width":70,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a1774aaa22314f88af162a98c91b5bfb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":99.9999923706055,
                          "y":520},
                        "size":{
                          "width":70,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 路况地图",
                              "target":{
                                "targetType":"page",
                                "url":"路况地图.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1121666d7b57497a9f140165fcc65f1e",
                  "label":"交通信息",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":295,
                      "y":520},
                    "size":{
                      "width":65,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"568e8882cc9f46c5a0de61f1e76e16e5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":295,
                          "y":520},
                        "size":{
                          "width":65,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 信息发布",
                              "target":{
                                "targetType":"page",
                                "url":"信息发布.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2ad8993dbb0c4226acf433be3c9a977a",
                  "label":"个人中心",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":185,
                      "y":746},
                    "size":{
                      "width":190,
                      "height":48},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8c32602116ad4fa7a53fae51e1449d48",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":185,
                          "y":746},
                        "size":{
                          "width":190,
                          "height":48},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 首页 to 个人中心",
                              "panelsToStates":[{
                                  "panelPath":["2fd825dc80094511a9eadab2ff51c181"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a35e33c3150348398b4bacf1d0030d4f",
                  "label":"车辆违法查询",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":6,
                      "y":369},
                    "size":{
                      "width":74,
                      "height":91},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7ae60d8ed1dd4bc9b85f773cf5730ded",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":6,
                          "y":369},
                        "size":{
                          "width":74,
                          "height":91},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 车辆交通违法查询",
                              "target":{
                                "targetType":"page",
                                "url":"车辆交通违法查询.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9483218ec0084054acd446701cf01854",
                  "label":"快撤快赔",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":303,
                      "y":220},
                    "size":{
                      "width":57,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"09d83f3f9dae4291aa2cc55c2f605a06",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":303,
                          "y":220},
                        "size":{
                          "width":57,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"已实名",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 快撤快赔首页",
                              "target":{
                                "targetType":"page",
                                "url":"快撤快赔首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]},
{
                          "description":"未实名",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 实名提示蒙版,<br>取消,<br>前往认证,<br>提示页面",
                              "objectsToFades":[{
                                  "objectPath":["92c03d86d8c348778a1da18f3da3ea95"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["ed2a0e6975de4da680b630ea7c9e773e"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["b57157b7ebfc4a60aa4e429de14f9093"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["afdc9524227a4862bd6828b387cde78e"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8850d085cc6345dfa01e6f84246055a6",
                  "label":"路况简图",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":195,
                      "y":520},
                    "size":{
                      "width":75,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"77e72f86fbe94120b86eae8ebda23c00",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":195,
                          "y":520},
                        "size":{
                          "width":75,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 路况简图",
                              "target":{
                                "targetType":"page",
                                "url":"路况简图.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"609e2c98ef4043128847a9d10e7e14a0",
                  "label":"六年免检",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":210,
                      "y":220},
                    "size":{
                      "width":60,
                      "height":55},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"29421d8b10924e35bdb06bbb9d6c2a5e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":210,
                          "y":220},
                        "size":{
                          "width":60,
                          "height":55},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"已实名",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 值于 page = &quot;14&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetGlobalVariableValue",
                                    "arguments":[{
                                        "exprType":"globalVariableLiteral",
                                        "variableName":"page"},
{
                                        "exprType":"stringLiteral",
                                        "value":"14",
                                        "stos":[]}]}]}},
{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 六年免检",
                              "target":{
                                "targetType":"page",
                                "url":"六年免检.html",
                                "includeVariables":true},
                              "linkType":"current"}]},
{
                          "description":"未实名",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 实名提示蒙版,<br>取消,<br>前往认证,<br>提示页面",
                              "objectsToFades":[{
                                  "objectPath":["92c03d86d8c348778a1da18f3da3ea95"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["ed2a0e6975de4da680b630ea7c9e773e"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["b57157b7ebfc4a60aa4e429de14f9093"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["afdc9524227a4862bd6828b387cde78e"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1f31bad596d040ed970774e98166cee6",
                  "label":"路况播报",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":10,
                      "y":520},
                    "size":{
                      "width":70,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5695eb88fa76442bb7a3c623b0156aa9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":10,
                          "y":520},
                        "size":{
                          "width":70,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 道路查询—展示",
                              "target":{
                                "targetType":"page",
                                "url":"道路查询—展示.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c1544399024444db861386cb7b4c3235",
                  "label":"交通违法缴罚",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":20,
                      "y":220},
                    "size":{
                      "width":60,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6a3e37c15eb942eb87918e005d0912b1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":20,
                          "y":220},
                        "size":{
                          "width":60,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"已实名",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 车辆交通违法缴罚",
                              "target":{
                                "targetType":"page",
                                "url":"车辆交通违法缴罚.html",
                                "includeVariables":true},
                              "linkType":"current"}]},
{
                          "description":"未实名",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 实名提示蒙版,<br>取消,<br>前往认证,<br>提示页面",
                              "objectsToFades":[{
                                  "objectPath":["92c03d86d8c348778a1da18f3da3ea95"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["ed2a0e6975de4da680b630ea7c9e773e"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["b57157b7ebfc4a60aa4e429de14f9093"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["afdc9524227a4862bd6828b387cde78e"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"92c03d86d8c348778a1da18f3da3ea95",
                  "label":"实名提示蒙版",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "opacity":"0.4",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000},
                    "size":{
                      "width":375,
                      "height":794},
                    "visible":false,
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e686752aa0fe476f8a031c6aae757fd2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "opacity":"0.4",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF000000},
                        "size":{
                          "width":375,
                          "height":794},
                        "visible":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/实名提示蒙版_u25.png"}},
{
                  "id":"afdc9524227a4862bd6828b387cde78e",
                  "label":"提示页面",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":19,
                      "y":280},
                    "size":{
                      "width":335,
                      "height":140},
                    "visible":false,
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0d0e98a152914a1bb8540eb159649dfc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":19,
                          "y":280},
                        "size":{
                          "width":335,
                          "height":140},
                        "visible":false,
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/提示页面_u27.png"}},
{
                  "id":"3a6255f18a374e1fb014a8700941cde7",
                  "label":"实名认证",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":286,
                      "y":375},
                    "size":{
                      "width":84,
                      "height":91},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c36e23a079ce42f1af68193becf0cf59",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":286,
                          "y":375},
                        "size":{
                          "width":84,
                          "height":91},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"未实名",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 取消,<br>前往认证,<br>实名提示蒙版,<br>提示页面",
                              "objectsToFades":[{
                                  "objectPath":["ed2a0e6975de4da680b630ea7c9e773e"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["b57157b7ebfc4a60aa4e429de14f9093"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["92c03d86d8c348778a1da18f3da3ea95"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["afdc9524227a4862bd6828b387cde78e"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]},
{
                          "description":"已实名",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 我的电子证件",
                              "target":{
                                "targetType":"page",
                                "url":"我的电子证件.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ed2a0e6975de4da680b630ea7c9e773e",
                  "label":"取消",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":25,
                      "y":374},
                    "size":{
                      "width":160,
                      "height":50},
                    "visible":false,
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2045fd0fe01b48ce804a1527b6c11c98",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":25,
                          "y":374},
                        "size":{
                          "width":160,
                          "height":50},
                        "visible":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 取消,<br>前往认证,<br>实名提示蒙版,<br>提示页面",
                              "objectsToFades":[{
                                  "objectPath":["ed2a0e6975de4da680b630ea7c9e773e"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["b57157b7ebfc4a60aa4e429de14f9093"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["92c03d86d8c348778a1da18f3da3ea95"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["afdc9524227a4862bd6828b387cde78e"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b57157b7ebfc4a60aa4e429de14f9093",
                  "label":"前往认证",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":195,
                      "y":374},
                    "size":{
                      "width":160,
                      "height":50},
                    "visible":false,
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"24611314bd51476aba951b040c45bc47",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":195,
                          "y":374},
                        "size":{
                          "width":160,
                          "height":50},
                        "visible":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"方案一",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 实名认证方案一",
                              "target":{
                                "targetType":"page",
                                "url":"实名认证方案一.html",
                                "includeVariables":true},
                              "linkType":"current"}]},
{
                          "description":"方案二",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 实名认证方案二",
                              "target":{
                                "targetType":"page",
                                "url":"实名认证方案二.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9b914a3f2080414ebc02a126f87d404b",
                  "label":"路况规划",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":650},
                    "size":{
                      "width":70,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0ab6010770104a0a988dcfc67d42ee94",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":650},
                        "size":{
                          "width":70,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 路线规划",
                              "target":{
                                "targetType":"page",
                                "url":"路线规划.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"a01334d7bbfb4e2aad1794670c13298a",
              "label":"个人中心",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7aaf191dcfd84888a6222777bf11682f",
                  "label":"",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":375,
                      "height":667}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8349237dd9324b44b8db661c80468c05",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":375,
                          "height":667}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u37.png"}},
{
                  "id":"9ed2803a6e1a447cbb05ae90e4933fa6",
                  "label":"",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":620},
                    "size":{
                      "width":190,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e29c2fc680a74be782f94c8d4242637b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":620},
                        "size":{
                          "width":190,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 首页 to 首页",
                              "panelsToStates":[{
                                  "panelPath":["2fd825dc80094511a9eadab2ff51c181"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a390d2d346fd4e53876538fb8a87092e",
                  "label":"我的路线",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":280},
                    "size":{
                      "width":380,
                      "height":51},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"647de495c2d7486985188e695ea79aba",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":280},
                        "size":{
                          "width":380,
                          "height":51},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 值于 page = &quot;5&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetGlobalVariableValue",
                                    "arguments":[{
                                        "exprType":"globalVariableLiteral",
                                        "variableName":"page"},
{
                                        "exprType":"stringLiteral",
                                        "value":"5",
                                        "stos":[]}]}]}},
{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 道路查询—展示",
                              "target":{
                                "targetType":"page",
                                "url":"道路查询—展示.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"32e1de6cc6204327809fb81cc9fb61e4",
                  "label":"我要申诉",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":335},
                    "size":{
                      "width":380,
                      "height":51},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0367897edb58492886ee26ed96b93a40",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":335},
                        "size":{
                          "width":380,
                          "height":51},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 我要申诉",
                              "target":{
                                "targetType":"page",
                                "url":"我要申诉.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6e8278ff9e694c76a2a6f0fbaf604dbb",
                  "label":"我的业务办理",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":388},
                    "size":{
                      "width":380,
                      "height":43},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b083fdf62d1042c8bb29ea3e9e141552",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":388},
                        "size":{
                          "width":380,
                          "height":43},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 业务办理进度",
                              "target":{
                                "targetType":"page",
                                "url":"业务办理进度.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6c15e977308d4e8f81e37ab8449a2bda",
                  "label":"电子证件",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":431},
                    "size":{
                      "width":380,
                      "height":51},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"899232b5e5804244be60e73218ac67f0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":431},
                        "size":{
                          "width":380,
                          "height":51},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 我的电子证件",
                              "target":{
                                "targetType":"page",
                                "url":"我的电子证件.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"aac8defd01144e85aa384206eb1f001d",
                  "label":"服务通知",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":236},
                    "size":{
                      "width":380,
                      "height":51},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8ff5bdd256384e039d083696f148bd0d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":236},
                        "size":{
                          "width":380,
                          "height":51},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 服务通知",
                              "target":{
                                "targetType":"page",
                                "url":"服务通知.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5a76ec7e51344a3587576b528e5e5268",
                  "label":"我的车辆",
                  "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":-1,
                      "y":482},
                    "size":{
                      "width":380,
                      "height":51},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e5bfd96c9cce4406ab9b237609b2c460",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd825dc80094511a9eadab2ff51c181",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":-1,
                          "y":482},
                        "size":{
                          "width":380,
                          "height":51},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 我的车辆",
                              "target":{
                                "targetType":"page",
                                "url":"我的车辆.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "2fd825dc80094511a9eadab2ff51c181":{
      "scriptId":"u0"},
    "7784b0ed65424ebcb4df24cdd8aeb39c":{
      "scriptId":"u1"},
    "41856e76ec7f46ccadbe1c7227912a29":{
      "scriptId":"u2"},
    "d9ffdfc373494d3496b90c0fab28a20c":{
      "scriptId":"u3"},
    "0f8f05a290164f1bb71f0d5a05ae858e":{
      "scriptId":"u4"},
    "f984c025a6854700b8a07f30867fd492":{
      "scriptId":"u5"},
    "4a1c38e616794754b9a37b07f1dbf0f5":{
      "scriptId":"u6"},
    "950aec15a75c49e29e30c599b8872a58":{
      "scriptId":"u7"},
    "a1774aaa22314f88af162a98c91b5bfb":{
      "scriptId":"u8"},
    "1121666d7b57497a9f140165fcc65f1e":{
      "scriptId":"u9"},
    "568e8882cc9f46c5a0de61f1e76e16e5":{
      "scriptId":"u10"},
    "2ad8993dbb0c4226acf433be3c9a977a":{
      "scriptId":"u11"},
    "8c32602116ad4fa7a53fae51e1449d48":{
      "scriptId":"u12"},
    "a35e33c3150348398b4bacf1d0030d4f":{
      "scriptId":"u13"},
    "7ae60d8ed1dd4bc9b85f773cf5730ded":{
      "scriptId":"u14"},
    "9483218ec0084054acd446701cf01854":{
      "scriptId":"u15"},
    "09d83f3f9dae4291aa2cc55c2f605a06":{
      "scriptId":"u16"},
    "8850d085cc6345dfa01e6f84246055a6":{
      "scriptId":"u17"},
    "77e72f86fbe94120b86eae8ebda23c00":{
      "scriptId":"u18"},
    "609e2c98ef4043128847a9d10e7e14a0":{
      "scriptId":"u19"},
    "29421d8b10924e35bdb06bbb9d6c2a5e":{
      "scriptId":"u20"},
    "1f31bad596d040ed970774e98166cee6":{
      "scriptId":"u21"},
    "5695eb88fa76442bb7a3c623b0156aa9":{
      "scriptId":"u22"},
    "c1544399024444db861386cb7b4c3235":{
      "scriptId":"u23"},
    "6a3e37c15eb942eb87918e005d0912b1":{
      "scriptId":"u24"},
    "92c03d86d8c348778a1da18f3da3ea95":{
      "scriptId":"u25"},
    "e686752aa0fe476f8a031c6aae757fd2":{
      "scriptId":"u26"},
    "afdc9524227a4862bd6828b387cde78e":{
      "scriptId":"u27"},
    "0d0e98a152914a1bb8540eb159649dfc":{
      "scriptId":"u28"},
    "3a6255f18a374e1fb014a8700941cde7":{
      "scriptId":"u29"},
    "c36e23a079ce42f1af68193becf0cf59":{
      "scriptId":"u30"},
    "ed2a0e6975de4da680b630ea7c9e773e":{
      "scriptId":"u31"},
    "2045fd0fe01b48ce804a1527b6c11c98":{
      "scriptId":"u32"},
    "b57157b7ebfc4a60aa4e429de14f9093":{
      "scriptId":"u33"},
    "24611314bd51476aba951b040c45bc47":{
      "scriptId":"u34"},
    "9b914a3f2080414ebc02a126f87d404b":{
      "scriptId":"u35"},
    "0ab6010770104a0a988dcfc67d42ee94":{
      "scriptId":"u36"},
    "7aaf191dcfd84888a6222777bf11682f":{
      "scriptId":"u37"},
    "8349237dd9324b44b8db661c80468c05":{
      "scriptId":"u38"},
    "9ed2803a6e1a447cbb05ae90e4933fa6":{
      "scriptId":"u39"},
    "e29c2fc680a74be782f94c8d4242637b":{
      "scriptId":"u40"},
    "a390d2d346fd4e53876538fb8a87092e":{
      "scriptId":"u41"},
    "647de495c2d7486985188e695ea79aba":{
      "scriptId":"u42"},
    "32e1de6cc6204327809fb81cc9fb61e4":{
      "scriptId":"u43"},
    "0367897edb58492886ee26ed96b93a40":{
      "scriptId":"u44"},
    "6e8278ff9e694c76a2a6f0fbaf604dbb":{
      "scriptId":"u45"},
    "b083fdf62d1042c8bb29ea3e9e141552":{
      "scriptId":"u46"},
    "6c15e977308d4e8f81e37ab8449a2bda":{
      "scriptId":"u47"},
    "899232b5e5804244be60e73218ac67f0":{
      "scriptId":"u48"},
    "aac8defd01144e85aa384206eb1f001d":{
      "scriptId":"u49"},
    "8ff5bdd256384e039d083696f148bd0d":{
      "scriptId":"u50"},
    "5a76ec7e51344a3587576b528e5e5268":{
      "scriptId":"u51"},
    "e5bfd96c9cce4406ab9b237609b2c460":{
      "scriptId":"u52"}}});