$axure.loadCurrentPage({
  "url":"上传完毕.html",
  "generationDate":new Date(1503556108966.26),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"page"],
  "page":{
    "packageId":"ee5a89743392487ea2b49704e6b71c1b",
    "type":"Axure:Page",
    "name":"上传完毕",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2b789227b200453889b3b50d359fb3e1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15e420eb54524bd7a75b58f00e6edd99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/上传完毕/u0.png"}},
{
          "id":"008f33ac7d3b4daa883b15fd109038bc",
          "label":"返回",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "textShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}},
            "location":{
              "x":0,
              "y":20},
            "size":{
              "width":70,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a940cd247f6d467098f9a052718bfb73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "textShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}},
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":70,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 证件上传",
                      "target":{
                        "targetType":"page",
                        "url":"证件上传.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4368ab9592ef41f287857eef12a24260",
          "label":"点击图片",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":190,
              "y":250.000015258789},
            "size":{
              "width":170,
              "height":110},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6aab43a4fd60427c878174189d03ea72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":190,
                  "y":250.000015258789},
                "size":{
                  "width":170,
                  "height":110},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 重新上传,<br>查看照片",
                      "objectsToFades":[{
                          "objectPath":["b06f622ff3c0402abd7f23907eb76b11"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f9dfad95a77e485fbe2e905f55d4653b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92ab5547568b402581065f5d10c6d0df",
          "label":"提交",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":10,
              "y":440},
            "size":{
              "width":350,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62c852525bda4403aa45368b78ea5a76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":10,
                  "y":440},
                "size":{
                  "width":350,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 申请成功",
                      "target":{
                        "targetType":"page",
                        "url":"申请成功.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9dfad95a77e485fbe2e905f55d4653b",
          "label":"查看照片",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "size":{
              "width":375,
              "height":667},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ec806b570254d9299fd7cc8103e2a75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "size":{
                  "width":375,
                  "height":667},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 查看照片,<br>重新上传",
                      "objectsToFades":[{
                          "objectPath":["f9dfad95a77e485fbe2e905f55d4653b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b06f622ff3c0402abd7f23907eb76b11"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/上传完毕/查看照片_u8.png"}},
{
          "id":"b06f622ff3c0402abd7f23907eb76b11",
          "label":"重新上传",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":120,
              "y":613},
            "size":{
              "width":130,
              "height":43},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"045717efcbe64456894feae2ecc0d5e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":120,
                  "y":613},
                "size":{
                  "width":130,
                  "height":43},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 证件上传",
                      "target":{
                        "targetType":"page",
                        "url":"证件上传.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9837ed8b45542a3840305a67914181c",
          "label":"证件图例",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":145,
              "y":510},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"046ee98b7dbf4c0c85e7ce650101995e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":145,
                  "y":510},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 图例2,<br>我知道了2",
                      "objectsToFades":[{
                          "objectPath":["d67ea545501f40698154b391c288c696"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["decd5920442d4ee0919e4e18ab9ee89b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d67ea545501f40698154b391c288c696",
          "label":"图例2",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "size":{
              "width":375,
              "height":667},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29a12602374c4f8692659f58b9a8286e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "size":{
                  "width":375,
                  "height":667},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 图例2,<br>我知道了2",
                      "objectsToFades":[{
                          "objectPath":["d67ea545501f40698154b391c288c696"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["decd5920442d4ee0919e4e18ab9ee89b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/证件上传/图例_u6.jpg"}},
{
          "id":"decd5920442d4ee0919e4e18ab9ee89b",
          "label":"我知道了2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":13,
              "y":427},
            "size":{
              "width":350,
              "height":65},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d62593261a564c33a1f447bbeab7fa90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":13,
                  "y":427},
                "size":{
                  "width":350,
                  "height":65},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 图例2,<br>我知道了2",
                      "objectsToFades":[{
                          "objectPath":["d67ea545501f40698154b391c288c696"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["decd5920442d4ee0919e4e18ab9ee89b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdc50b7464184bb88796025e3a79e5a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":400,
              "y":98},
            "size":{
              "width":150,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7349d3c2bead402794d16637c9b11e66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":400,
                  "y":98},
                "size":{
                  "width":150,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实名认证方案一/u6.png"}},
{
          "id":"9cde69aa010d4ebaa5c62ce610e7d851",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":140},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cdf70ed83b24a33ab0da8517e50eff6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":140},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"0717eb9777354f8aafff4ccf2840e64b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":210},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"470397c0a734495d898a2d6905d82dc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":210},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"353f3aa14832424c81fc99f75f90b12d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":570,
              "y":140},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9802922d9c654149a0448b2650716a6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":570,
                  "y":140},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"044e3805f01546e9b9738ceecfeeb01a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":155},
            "size":{
              "width":20,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/实名认证方案一/u14_end.png",
            "line~":"images/实名认证方案一/u14_line.png"}},
{
          "id":"113e245d710645269aaeb1ea9f335c60",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":190},
            "size":{
              "width":20,
              "height":10},
            "rotation":"90"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/实名认证方案一/u14_end.png",
            "line~":"images/实名认证方案一/u14_line.png"}},
{
          "id":"d22b55f8a3e54a15a6e0ef4951cdd4f0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":225},
            "size":{
              "width":20,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/实名认证方案一/u14_end.png",
            "line~":"images/实名认证方案一/u14_line.png"}},
{
          "id":"3387d0a643e2479eab1df0ede632126c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":570,
              "y":190},
            "size":{
              "width":130,
              "height":80},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c492701940d24b7aa500b05d3fbf2314",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":570,
                  "y":190},
                "size":{
                  "width":130,
                  "height":80},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实名认证方案一/u17.png"}},
{
          "id":"d34dda8b9de34b8fbb45fdafe1f84643",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":280},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b80332cda9964c4582bb4c068057c8eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":280},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"2053c6bf4685402f97f51390abb53f3d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":255},
            "size":{
              "width":20,
              "height":10},
            "rotation":"90"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/实名认证方案一/u14_end.png",
            "line~":"images/实名认证方案一/u14_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2b789227b200453889b3b50d359fb3e1":{
      "scriptId":"u0"},
    "15e420eb54524bd7a75b58f00e6edd99":{
      "scriptId":"u1"},
    "008f33ac7d3b4daa883b15fd109038bc":{
      "scriptId":"u2"},
    "a940cd247f6d467098f9a052718bfb73":{
      "scriptId":"u3"},
    "4368ab9592ef41f287857eef12a24260":{
      "scriptId":"u4"},
    "6aab43a4fd60427c878174189d03ea72":{
      "scriptId":"u5"},
    "92ab5547568b402581065f5d10c6d0df":{
      "scriptId":"u6"},
    "62c852525bda4403aa45368b78ea5a76":{
      "scriptId":"u7"},
    "f9dfad95a77e485fbe2e905f55d4653b":{
      "scriptId":"u8"},
    "0ec806b570254d9299fd7cc8103e2a75":{
      "scriptId":"u9"},
    "b06f622ff3c0402abd7f23907eb76b11":{
      "scriptId":"u10"},
    "045717efcbe64456894feae2ecc0d5e7":{
      "scriptId":"u11"},
    "c9837ed8b45542a3840305a67914181c":{
      "scriptId":"u12"},
    "046ee98b7dbf4c0c85e7ce650101995e":{
      "scriptId":"u13"},
    "d67ea545501f40698154b391c288c696":{
      "scriptId":"u14"},
    "29a12602374c4f8692659f58b9a8286e":{
      "scriptId":"u15"},
    "decd5920442d4ee0919e4e18ab9ee89b":{
      "scriptId":"u16"},
    "d62593261a564c33a1f447bbeab7fa90":{
      "scriptId":"u17"},
    "cdc50b7464184bb88796025e3a79e5a4":{
      "scriptId":"u18"},
    "7349d3c2bead402794d16637c9b11e66":{
      "scriptId":"u19"},
    "9cde69aa010d4ebaa5c62ce610e7d851":{
      "scriptId":"u20"},
    "9cdf70ed83b24a33ab0da8517e50eff6":{
      "scriptId":"u21"},
    "0717eb9777354f8aafff4ccf2840e64b":{
      "scriptId":"u22"},
    "470397c0a734495d898a2d6905d82dc3":{
      "scriptId":"u23"},
    "353f3aa14832424c81fc99f75f90b12d":{
      "scriptId":"u24"},
    "9802922d9c654149a0448b2650716a6c":{
      "scriptId":"u25"},
    "044e3805f01546e9b9738ceecfeeb01a":{
      "scriptId":"u26"},
    "113e245d710645269aaeb1ea9f335c60":{
      "scriptId":"u27"},
    "d22b55f8a3e54a15a6e0ef4951cdd4f0":{
      "scriptId":"u28"},
    "3387d0a643e2479eab1df0ede632126c":{
      "scriptId":"u29"},
    "c492701940d24b7aa500b05d3fbf2314":{
      "scriptId":"u30"},
    "d34dda8b9de34b8fbb45fdafe1f84643":{
      "scriptId":"u31"},
    "b80332cda9964c4582bb4c068057c8eb":{
      "scriptId":"u32"},
    "2053c6bf4685402f97f51390abb53f3d":{
      "scriptId":"u33"}}});