$axure.loadCurrentPage({
  "url":"快撤快赔首页.html",
  "generationDate":new Date(1503556107123.16),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"page"],
  "page":{
    "packageId":"bfbe598dcdaa4912a00c75ae714aabd3",
    "type":"Axure:Page",
    "name":"快撤快赔首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2175cf95f2604146af84898138159585",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84589e3757a2426b93df9869306057f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u0.png"}},
{
          "id":"1b5986e5457d42c48002dc928641be3e",
          "label":"返回",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":50,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4f696df65a54ca29c2563193a9c9399",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":50,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1aaf56030b649548a1fdfa9c479244d",
          "label":"返回",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":140,
              "y":180},
            "size":{
              "width":100,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8181ce0e448a4e1bb5f849b51db56c04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":140,
                  "y":180},
                "size":{
                  "width":100,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 快撤快赔—温馨提示",
                      "target":{
                        "targetType":"page",
                        "url":"快撤快赔—温馨提示.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a48532a90ebc4c7b9ecadce7cdc43b3e",
          "label":"返回",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":140,
              "y":300},
            "size":{
              "width":100,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d32edbe25634e508640c3356cb27034",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":140,
                  "y":300},
                "size":{
                  "width":100,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 事故情形选择",
                      "target":{
                        "targetType":"page",
                        "url":"事故情形选择.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64325923b5254eb9b7d031ab7a758ac5",
          "label":"返回",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":140,
              "y":430},
            "size":{
              "width":100,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a06fbd4797fc41829feead45eddf4db2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":140,
                  "y":430},
                "size":{
                  "width":100,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 保险报案说明",
                      "target":{
                        "targetType":"page",
                        "url":"保险报案说明.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a432579c7a904dd6885a42c3e9051878",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":0},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a1c6ba824694fdfb5cb8fdff4ed1c65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":0},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"e54f28e9f24840fba809413de62d2167",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":50},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a547c72df3184e09ac5a2bf11fd87db1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":50},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"a2df3027b0054b9ebee424bcef30d5c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":100},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a404207206ad4a2ea22302ebf5304736",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":100},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"04536906102f419f8dbbb504dc2cef6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":150},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3300FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05ed7d4c051848da8a591947276bf1bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":150},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3300FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u16.png"}},
{
          "id":"6a43bad734af412d87fb6a184946c79d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":200},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83efdb409cf4479bab609402b4ae30d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":200},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"d70e5d4a154741dd80a72e14d3eceef4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":250},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3300FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65647722b1654d4593513178d06dbea5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":250},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3300FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u16.png"}},
{
          "id":"5c5f8f8924c64be9b23621ffcd79942a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":300},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c28003038444c2cb74538e8e613ccac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":300},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"1999ad021aae43f0a5ee47e6e8e8c6e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":350},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"658a862c5da14cac991dd1fcf7d6418f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":350},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"3b63e9cff36f4f799f57a3f67befd305",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":400},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acda5bbb7e6040c982fd27beba372e86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":400},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"94ff8e71c4e749caa3e4b70a5c3ec451",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":450},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"516cacbdf5984048ac719878e1143840",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":450},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"e1afaa764ebf409d9669b8d4a6c515a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":500},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3300FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55dd7d6caa87430cbdf57f89b5727aff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":500},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3300FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u16.png"}},
{
          "id":"c2a6db7033e442cfa5fe341970571d7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":550},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e4fa2a4a4e54edbb9f6ac01d45b1be9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":550},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"679652b21c904d98b5ac0549ce539f6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":600},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"550143fc98e4456da853fb851c01cb54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":600},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"ed95949d349a42f088d1e95a040a4222",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":650},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a48eb9566814fb3a441be700eccbc04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":650},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"16dbc91ed7414d73af247a1e0a037078",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":700},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa8d06533b8246b9882eb747ae6e9107",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":700},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2175cf95f2604146af84898138159585":{
      "scriptId":"u0"},
    "84589e3757a2426b93df9869306057f3":{
      "scriptId":"u1"},
    "1b5986e5457d42c48002dc928641be3e":{
      "scriptId":"u2"},
    "b4f696df65a54ca29c2563193a9c9399":{
      "scriptId":"u3"},
    "d1aaf56030b649548a1fdfa9c479244d":{
      "scriptId":"u4"},
    "8181ce0e448a4e1bb5f849b51db56c04":{
      "scriptId":"u5"},
    "a48532a90ebc4c7b9ecadce7cdc43b3e":{
      "scriptId":"u6"},
    "1d32edbe25634e508640c3356cb27034":{
      "scriptId":"u7"},
    "64325923b5254eb9b7d031ab7a758ac5":{
      "scriptId":"u8"},
    "a06fbd4797fc41829feead45eddf4db2":{
      "scriptId":"u9"},
    "a432579c7a904dd6885a42c3e9051878":{
      "scriptId":"u10"},
    "5a1c6ba824694fdfb5cb8fdff4ed1c65":{
      "scriptId":"u11"},
    "e54f28e9f24840fba809413de62d2167":{
      "scriptId":"u12"},
    "a547c72df3184e09ac5a2bf11fd87db1":{
      "scriptId":"u13"},
    "a2df3027b0054b9ebee424bcef30d5c4":{
      "scriptId":"u14"},
    "a404207206ad4a2ea22302ebf5304736":{
      "scriptId":"u15"},
    "04536906102f419f8dbbb504dc2cef6a":{
      "scriptId":"u16"},
    "05ed7d4c051848da8a591947276bf1bf":{
      "scriptId":"u17"},
    "6a43bad734af412d87fb6a184946c79d":{
      "scriptId":"u18"},
    "83efdb409cf4479bab609402b4ae30d5":{
      "scriptId":"u19"},
    "d70e5d4a154741dd80a72e14d3eceef4":{
      "scriptId":"u20"},
    "65647722b1654d4593513178d06dbea5":{
      "scriptId":"u21"},
    "5c5f8f8924c64be9b23621ffcd79942a":{
      "scriptId":"u22"},
    "9c28003038444c2cb74538e8e613ccac":{
      "scriptId":"u23"},
    "1999ad021aae43f0a5ee47e6e8e8c6e9":{
      "scriptId":"u24"},
    "658a862c5da14cac991dd1fcf7d6418f":{
      "scriptId":"u25"},
    "3b63e9cff36f4f799f57a3f67befd305":{
      "scriptId":"u26"},
    "acda5bbb7e6040c982fd27beba372e86":{
      "scriptId":"u27"},
    "94ff8e71c4e749caa3e4b70a5c3ec451":{
      "scriptId":"u28"},
    "516cacbdf5984048ac719878e1143840":{
      "scriptId":"u29"},
    "e1afaa764ebf409d9669b8d4a6c515a7":{
      "scriptId":"u30"},
    "55dd7d6caa87430cbdf57f89b5727aff":{
      "scriptId":"u31"},
    "c2a6db7033e442cfa5fe341970571d7a":{
      "scriptId":"u32"},
    "7e4fa2a4a4e54edbb9f6ac01d45b1be9":{
      "scriptId":"u33"},
    "679652b21c904d98b5ac0549ce539f6a":{
      "scriptId":"u34"},
    "550143fc98e4456da853fb851c01cb54":{
      "scriptId":"u35"},
    "ed95949d349a42f088d1e95a040a4222":{
      "scriptId":"u36"},
    "4a48eb9566814fb3a441be700eccbc04":{
      "scriptId":"u37"},
    "16dbc91ed7414d73af247a1e0a037078":{
      "scriptId":"u38"},
    "aa8d06533b8246b9882eb747ae6e9107":{
      "scriptId":"u39"}}});