$axure.loadCurrentPage({
  "url":"收件信息填写.html",
  "generationDate":new Date(1503556105746.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"page"],
  "page":{
    "packageId":"7c16c8b733d443f0acecf3aa86951499",
    "type":"Axure:Page",
    "name":"收件信息填写",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4718e5ea7fef423fabf4c4ee7e54fb83",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"837cf635b8134b5aa5c886f9afbff444",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收件信息填写/u0.png"}},
{
          "id":"3c124978e3ca4da1a78125087fc951a6",
          "label":"返回",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":70,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b197abcad75547e69decc56d780b3d37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":70,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 照片上传",
                      "target":{
                        "targetType":"page",
                        "url":"照片上传.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"068d079deaa04332812ffd15e1ccd2d3",
          "label":"提交订单",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":10,
              "y":400},
            "size":{
              "width":350,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e41b32245a84421b5b04b55bb1f8bd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":10,
                  "y":400},
                "size":{
                  "width":350,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 提示,<br>确定,<br>取消",
                      "objectsToFades":[{
                          "objectPath":["7e669e459d2245afb5e06795fe8675b6"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2572f30514af4887b2693937488f5108"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["e67ac0a418924c879e5213284e2a519d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e669e459d2245afb5e06795fe8675b6",
          "label":"提示",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "size":{
              "width":375,
              "height":667},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af910234252645a7a3604a2d977df715",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "size":{
                  "width":375,
                  "height":667},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收件信息填写/提示_u6.png"}},
{
          "id":"2572f30514af4887b2693937488f5108",
          "label":"确定",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":203,
              "y":597},
            "size":{
              "width":127,
              "height":57},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"188d4626402e4aea969dcafd50c65381",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":203,
                  "y":597},
                "size":{
                  "width":127,
                  "height":57},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 确定资料",
                      "target":{
                        "targetType":"page",
                        "url":"确定资料.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e67ac0a418924c879e5213284e2a519d",
          "label":"取消",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":43,
              "y":597},
            "size":{
              "width":127,
              "height":57},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8b649340b70472ba3b756c39b4c9a88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":43,
                  "y":597},
                "size":{
                  "width":127,
                  "height":57},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 提示,<br>确定,<br>取消",
                      "objectsToFades":[{
                          "objectPath":["7e669e459d2245afb5e06795fe8675b6"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2572f30514af4887b2693937488f5108"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["e67ac0a418924c879e5213284e2a519d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a043a748f9644ad181825fde4fa022a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":83},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"132521e156d641cb814d8534ea57ccde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":83},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}},
{
          "id":"c785d686ea1043fa81dd189a1c4661a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":150},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c9b2418798e49e7a28f6b2e3a5c359e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":150},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}},
{
          "id":"7fa3a16eb8b64024ab1bf75b15986cf3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":217},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"915ee0215a3743938de06b40e600bd60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":217},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}},
{
          "id":"55e00f427d5a43d4acb4590dd7fcd278",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":284},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30bb2c7de20849de8949f522dee4f787",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":284},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}},
{
          "id":"62fefdeef8214359bc32c0ed5e3cc4dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":351},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67e821ed449a422f95eac938706310ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":351},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4718e5ea7fef423fabf4c4ee7e54fb83":{
      "scriptId":"u0"},
    "837cf635b8134b5aa5c886f9afbff444":{
      "scriptId":"u1"},
    "3c124978e3ca4da1a78125087fc951a6":{
      "scriptId":"u2"},
    "b197abcad75547e69decc56d780b3d37":{
      "scriptId":"u3"},
    "068d079deaa04332812ffd15e1ccd2d3":{
      "scriptId":"u4"},
    "3e41b32245a84421b5b04b55bb1f8bd4":{
      "scriptId":"u5"},
    "7e669e459d2245afb5e06795fe8675b6":{
      "scriptId":"u6"},
    "af910234252645a7a3604a2d977df715":{
      "scriptId":"u7"},
    "2572f30514af4887b2693937488f5108":{
      "scriptId":"u8"},
    "188d4626402e4aea969dcafd50c65381":{
      "scriptId":"u9"},
    "e67ac0a418924c879e5213284e2a519d":{
      "scriptId":"u10"},
    "b8b649340b70472ba3b756c39b4c9a88":{
      "scriptId":"u11"},
    "a043a748f9644ad181825fde4fa022a5":{
      "scriptId":"u12"},
    "132521e156d641cb814d8534ea57ccde":{
      "scriptId":"u13"},
    "c785d686ea1043fa81dd189a1c4661a5":{
      "scriptId":"u14"},
    "5c9b2418798e49e7a28f6b2e3a5c359e":{
      "scriptId":"u15"},
    "7fa3a16eb8b64024ab1bf75b15986cf3":{
      "scriptId":"u16"},
    "915ee0215a3743938de06b40e600bd60":{
      "scriptId":"u17"},
    "55e00f427d5a43d4acb4590dd7fcd278":{
      "scriptId":"u18"},
    "30bb2c7de20849de8949f522dee4f787":{
      "scriptId":"u19"},
    "62fefdeef8214359bc32c0ed5e3cc4dc":{
      "scriptId":"u20"},
    "67e821ed449a422f95eac938706310ba":{
      "scriptId":"u21"}}});