$axure.loadCurrentPage({
  "url":"确定资料.html",
  "generationDate":new Date(1503556105782.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"page"],
  "page":{
    "packageId":"223a61b20d034b3ebf9a48ebed5a7ade",
    "type":"Axure:Page",
    "name":"确定资料",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"251efdf51e6649e3b68f3a40a42f0c29",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b5da8311a0b4fc99add224d27511467",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确定资料/u0.png"}},
{
          "id":"f543790082b743bea12927dca2125c5b",
          "label":"返回",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":70,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50439ef320704831a26ed2bb8b76ebfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":70,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 收件信息填写",
                      "target":{
                        "targetType":"page",
                        "url":"收件信息填写.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7057ee8dfca54384a118a1ce35401904",
          "label":"确定",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":230,
              "y":620},
            "size":{
              "width":145,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18f5a71d8e7a4ff18be5caf7fa507290",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":230,
                  "y":620},
                "size":{
                  "width":145,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 支付成功",
                      "target":{
                        "targetType":"page",
                        "url":"支付成功_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1235717e5994460786ed970dc45c6a11",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":83},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a936bdb65ca4731b18d0e34a809014e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":83},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}},
{
          "id":"09963e164b7d4e5ea705f38e9af309f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":150},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fb2c937578d4e1cb796aa22e981c7d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":150},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}},
{
          "id":"2bb51f4c0e1d41f7bae95ec8b025bc02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":217},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b2b8c92f6004debbaed90581f9dc0ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":217},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}},
{
          "id":"59cf68b4ed6049528744f1920dfccbe9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":284},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"487f7e6a576e4895a8222f0d4b65c574",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":284},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}},
{
          "id":"9dbf30cdf94e42089fb6464eed6a0937",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":351},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7515ebf5c03448eae56b78001fb3ae6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":351},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "251efdf51e6649e3b68f3a40a42f0c29":{
      "scriptId":"u0"},
    "7b5da8311a0b4fc99add224d27511467":{
      "scriptId":"u1"},
    "f543790082b743bea12927dca2125c5b":{
      "scriptId":"u2"},
    "50439ef320704831a26ed2bb8b76ebfc":{
      "scriptId":"u3"},
    "7057ee8dfca54384a118a1ce35401904":{
      "scriptId":"u4"},
    "18f5a71d8e7a4ff18be5caf7fa507290":{
      "scriptId":"u5"},
    "1235717e5994460786ed970dc45c6a11":{
      "scriptId":"u6"},
    "8a936bdb65ca4731b18d0e34a809014e":{
      "scriptId":"u7"},
    "09963e164b7d4e5ea705f38e9af309f7":{
      "scriptId":"u8"},
    "2fb2c937578d4e1cb796aa22e981c7d1":{
      "scriptId":"u9"},
    "2bb51f4c0e1d41f7bae95ec8b025bc02":{
      "scriptId":"u10"},
    "4b2b8c92f6004debbaed90581f9dc0ab":{
      "scriptId":"u11"},
    "59cf68b4ed6049528744f1920dfccbe9":{
      "scriptId":"u12"},
    "487f7e6a576e4895a8222f0d4b65c574":{
      "scriptId":"u13"},
    "9dbf30cdf94e42089fb6464eed6a0937":{
      "scriptId":"u14"},
    "d7515ebf5c03448eae56b78001fb3ae6":{
      "scriptId":"u15"}}});