$axure.loadCurrentPage({
  "url":"路段快照详情.html",
  "generationDate":new Date(1503556106510.12),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"page"],
  "page":{
    "packageId":"96e5ccaa0be143dd92acfd0c1cfbc7cf",
    "type":"Axure:Page",
    "name":"路段快照详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1aaa4cdc2b3b418a8f26848bb6b3091e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1003dc19a73446de9f9f4a58d9be5e57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/路段快照详情/u0.png"}},
{
          "id":"d145ab5c6c384176ba3329c243133c9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":-10,
              "y":20},
            "size":{
              "width":90,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2de6f9eb3914dc28b59d72b77184955",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":-10,
                  "y":20},
                "size":{
                  "width":90,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 道路查询—展示",
                      "target":{
                        "targetType":"page",
                        "url":"道路查询—展示.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6b7520b3356489c96d4a2dd627b623b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":440,
              "y":272},
            "size":{
              "width":250,
              "height":208}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61a15536dec94836a6cff0f4b51c98d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":440,
                  "y":272},
                "size":{
                  "width":250,
                  "height":208}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/路段快照详情/u4.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "1aaa4cdc2b3b418a8f26848bb6b3091e":{
      "scriptId":"u0"},
    "1003dc19a73446de9f9f4a58d9be5e57":{
      "scriptId":"u1"},
    "d145ab5c6c384176ba3329c243133c9d":{
      "scriptId":"u2"},
    "a2de6f9eb3914dc28b59d72b77184955":{
      "scriptId":"u3"},
    "e6b7520b3356489c96d4a2dd627b623b":{
      "scriptId":"u4"},
    "61a15536dec94836a6cff0f4b51c98d2":{
      "scriptId":"u5"}}});