$axure.loadCurrentPage({
  "url":"一键移车—提交申请.html",
  "generationDate":new Date(1503556106193.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"page"],
  "page":{
    "packageId":"f352770860a4426dbca621268e6a5b16",
    "type":"Axure:Page",
    "name":"一键移车—提交申请",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c732d0fa207944b99e99560cb3ba3fd6",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":930,
              "height":860}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"d5c82c481d414aad94873f3627d17fea",
              "label":"移车",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b130cc12976e40938101f768dcc3418f",
                  "label":"",
                  "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":375,
                      "height":850}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2e31f02945f443aa83149b37b37aa51b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":375,
                          "height":850}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/一键移车—提交申请/u1.png"}},
{
                  "id":"02acaa8a63ba4c7781fa80fb7466434f",
                  "label":"移车卡按钮",
                  "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":185,
                      "y":60},
                    "size":{
                      "width":190,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c4420f1de3574fe096c337b4adbc5769",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":185,
                          "y":60},
                        "size":{
                          "width":190,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 卡",
                              "panelsToStates":[{
                                  "panelPath":["c732d0fa207944b99e99560cb3ba3fd6"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b11b7ba5cb624fc982502fa254f20cf4",
                  "label":"提交移车申请按钮",
                  "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":5,
                      "y":650},
                    "size":{
                      "width":370,
                      "height":70},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7fc128edae92463fb1ef7ab0c207268b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":5,
                          "y":650},
                        "size":{
                          "width":370,
                          "height":70},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 提示,<br>蒙版,<br>确定按钮,<br>关闭按钮",
                              "objectsToFades":[{
                                  "objectPath":["148c35990f64441c905efbac17d9e73c"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["0bccb38b9e5545e896ade38b8fc989c2"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["47a4e99616b04566bcfdc2900180b38b"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["a9f3f3b518e24113be9bd45c50bcd4ef"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 (图片)",
                              "objectsToFades":[{
                                  "objectPath":["b130cc12976e40938101f768dcc3418f"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f61854289230462f83f531743716c63e",
                  "label":"加号按钮",
                  "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":80,
                      "y":560},
                    "size":{
                      "width":80,
                      "height":70},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ac99cebf245a41c794bbf6e0298ab6c7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":80,
                          "y":560},
                        "size":{
                          "width":80,
                          "height":70},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 拍照,<br>取消按钮",
                              "objectsToFades":[{
                                  "objectPath":["8219c223e3264d17bf5c78f6b04358aa"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["5dd88b0f1d4740628cf8ff8749a9a913"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 (图片)",
                              "objectsToFades":[{
                                  "objectPath":["b130cc12976e40938101f768dcc3418f"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0bccb38b9e5545e896ade38b8fc989c2",
                  "label":"蒙版",
                  "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "opacity":"0.7",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000},
                    "size":{
                      "width":375,
                      "height":667},
                    "visible":false,
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"829fbb9ac491486fb096db1d62d2db90",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "opacity":"0.7",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF000000},
                        "size":{
                          "width":375,
                          "height":667},
                        "visible":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/一键移车—提交申请/蒙版_u9.png"}},
{
                  "id":"a9f3f3b518e24113be9bd45c50bcd4ef",
                  "label":"关闭按钮",
                  "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":333,
                      "y":177},
                    "size":{
                      "width":29,
                      "height":26},
                    "visible":false,
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1381fc586bfd4ca0a52642e354af738c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":333,
                          "y":177},
                        "size":{
                          "width":29,
                          "height":26},
                        "visible":false,
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 蒙版,<br>提示,<br>关闭按钮,<br>确定按钮",
                              "objectsToFades":[{
                                  "objectPath":["0bccb38b9e5545e896ade38b8fc989c2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["148c35990f64441c905efbac17d9e73c"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["a9f3f3b518e24113be9bd45c50bcd4ef"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["47a4e99616b04566bcfdc2900180b38b"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"显示 (图片)",
                              "objectsToFades":[{
                                  "objectPath":["b130cc12976e40938101f768dcc3418f"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/一键移车—提交申请/关闭按钮_u11.png"}},
{
                  "id":"8219c223e3264d17bf5c78f6b04358aa",
                  "label":"拍照",
                  "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":false,
                  "style":{
                    "size":{
                      "width":375,
                      "height":667},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"12bfd0db6655492199a63e30f788b340",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "size":{
                          "width":375,
                          "height":667},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/一键移车—提交申请/拍照_u13.png"}},
{
                  "id":"5dd88b0f1d4740628cf8ff8749a9a913",
                  "label":"取消按钮",
                  "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":5,
                      "y":616},
                    "size":{
                      "width":370,
                      "height":51},
                    "visible":false,
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"74377155a6e84eb6afa87ed920435b34",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":5,
                          "y":616},
                        "size":{
                          "width":370,
                          "height":51},
                        "visible":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 取消按钮,<br>拍照",
                              "objectsToFades":[{
                                  "objectPath":["5dd88b0f1d4740628cf8ff8749a9a913"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["8219c223e3264d17bf5c78f6b04358aa"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"显示 (图片)",
                              "objectsToFades":[{
                                  "objectPath":["b130cc12976e40938101f768dcc3418f"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"148c35990f64441c905efbac17d9e73c",
                  "label":"提示",
                  "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":10,
                      "y":213},
                    "size":{
                      "width":349,
                      "height":239},
                    "visible":false,
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7f4bf1624b794a9491251114dd0e5ca5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":10,
                          "y":213},
                        "size":{
                          "width":349,
                          "height":239},
                        "visible":false,
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/一键移车—提交申请/提示_u17.png"}},
{
                  "id":"47a4e99616b04566bcfdc2900180b38b",
                  "label":"确定按钮",
                  "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":30,
                      "y":380},
                    "size":{
                      "width":320,
                      "height":50},
                    "visible":false,
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"15faf501aa754cc0822ced68252b5f8f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":30,
                          "y":380},
                        "size":{
                          "width":320,
                          "height":50},
                        "visible":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 一键移车—完成提醒",
                              "target":{
                                "targetType":"page",
                                "url":"一键移车—完成提醒.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"c43a9180939c48ab925a58641d6daa08",
              "label":"卡",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"08a4216d297f4a148b141bbb80380b0f",
                  "label":"",
                  "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":375,
                      "height":667}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a7b07d34aa3d4151b374585c453e0f02",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":375,
                          "height":667}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/一键移车—提交申请/u21.png"}},
{
                  "id":"c2b2fb012e9240f397dbb7f139828dce",
                  "label":"一键移车按钮",
                  "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":190,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fca59f4631ec4c66a608e343991cd754",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":60},
                        "size":{
                          "width":190,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 移车",
                              "panelsToStates":[{
                                  "panelPath":["c732d0fa207944b99e99560cb3ba3fd6"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3f8cf07df06a4f2591be071677a812b7",
                  "label":"生成代码",
                  "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":10,
                      "y":330},
                    "size":{
                      "width":365,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cd6f67ad934047d0a954f6cfc8159f61",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":10,
                          "y":330},
                        "size":{
                          "width":365,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 移车卡生成页面,<br>返回",
                              "objectsToFades":[{
                                  "objectPath":["368ff5559b1e444c952e167dfd9349ee"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["2b4659b510ee4050b39451d97fa02e30"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"368ff5559b1e444c952e167dfd9349ee",
                  "label":"移车卡生成页面",
                  "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":false,
                  "style":{
                    "size":{
                      "width":375,
                      "height":667},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c5e6b3048b3144a8a75e0236d30dcc2c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "size":{
                          "width":375,
                          "height":667},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/一键移车—提交申请/移车卡生成页面_u27.png"}},
{
                  "id":"2b4659b510ee4050b39451d97fa02e30",
                  "label":"返回",
                  "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":17},
                    "size":{
                      "width":75,
                      "height":40},
                    "visible":false,
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"13aeaef076bb48418d60896bf4ab8cd5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c732d0fa207944b99e99560cb3ba3fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":17},
                        "size":{
                          "width":75,
                          "height":40},
                        "visible":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 移车卡生成页面,<br>返回",
                              "objectsToFades":[{
                                  "objectPath":["368ff5559b1e444c952e167dfd9349ee"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["2b4659b510ee4050b39451d97fa02e30"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"26c2fc9759b942a5aabc7fc9b9218143",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":-10,
              "y":20},
            "size":{
              "width":90,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0466aba4c80b437d81284e24668dfae5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":-10,
                  "y":20},
                "size":{
                  "width":90,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09a7cb536b624fee928539e28210185a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":160},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d6b3fcad04a4b9ca95b63834f205106",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":160},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}},
{
          "id":"226abf69f21540e98d78e7e514b1875b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":455,
              "y":58},
            "size":{
              "width":60,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41530a4a967d4d55ada513be9d0f8380",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":455,
                  "y":58},
                "size":{
                  "width":60,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eddf2c7873c14747ba1d668d86fd7b55",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":630,
              "y":73},
            "size":{
              "width":190,
              "height":77},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2107c5cfd3f24bf39ccf855f7c3e053e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":630,
                  "y":73},
                "size":{
                  "width":190,
                  "height":77},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一键移车—提交申请/u37.png"}},
{
          "id":"633f31b604fa439998cae00b28c4de8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":658,
              "y":58},
            "size":{
              "width":75,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebbafb550390497291019a63263ab6e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":658,
                  "y":58},
                "size":{
                  "width":75,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f307ab8035e4d45b18bab266b93a19c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":630,
              "y":170},
            "size":{
              "width":190,
              "height":60},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d288a369aee4592b6d3befcbd715855",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":630,
                  "y":170},
                "size":{
                  "width":190,
                  "height":60},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一键移车—提交申请/u41.png"}},
{
          "id":"5826908d91d546699dbd18704547bc64",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":630,
              "y":240},
            "size":{
              "width":190,
              "height":36},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0212b0dd2a4467baad9fed228058d04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":630,
                  "y":240},
                "size":{
                  "width":190,
                  "height":36},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一键移车—提交申请/u43.png"}},
{
          "id":"e36439af79fa438586662d955c1bde01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":630,
              "y":293},
            "size":{
              "width":190,
              "height":77},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"742bdc88dd2e4bb897d929f0c1155111",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":630,
                  "y":293},
                "size":{
                  "width":190,
                  "height":77},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一键移车—提交申请/u37.png"}},
{
          "id":"5690101644f2479dbf36f94ce325bf08",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":93},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8c5027acf574c858fb822ccf0d0f1de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":93},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}},
{
          "id":"4ffe350bbe924d6c8cfad573e5909af7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":227.000015258789},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53f03e2084f248ffb0dda6d94885ebe0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":227.000015258789},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}},
{
          "id":"751ffeab1b584d8a8cd3272bbbb600bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":294},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"895059f4319a47d49a8403c4a2e2916e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":294},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c732d0fa207944b99e99560cb3ba3fd6":{
      "scriptId":"u0"},
    "b130cc12976e40938101f768dcc3418f":{
      "scriptId":"u1"},
    "2e31f02945f443aa83149b37b37aa51b":{
      "scriptId":"u2"},
    "02acaa8a63ba4c7781fa80fb7466434f":{
      "scriptId":"u3"},
    "c4420f1de3574fe096c337b4adbc5769":{
      "scriptId":"u4"},
    "b11b7ba5cb624fc982502fa254f20cf4":{
      "scriptId":"u5"},
    "7fc128edae92463fb1ef7ab0c207268b":{
      "scriptId":"u6"},
    "f61854289230462f83f531743716c63e":{
      "scriptId":"u7"},
    "ac99cebf245a41c794bbf6e0298ab6c7":{
      "scriptId":"u8"},
    "0bccb38b9e5545e896ade38b8fc989c2":{
      "scriptId":"u9"},
    "829fbb9ac491486fb096db1d62d2db90":{
      "scriptId":"u10"},
    "a9f3f3b518e24113be9bd45c50bcd4ef":{
      "scriptId":"u11"},
    "1381fc586bfd4ca0a52642e354af738c":{
      "scriptId":"u12"},
    "8219c223e3264d17bf5c78f6b04358aa":{
      "scriptId":"u13"},
    "12bfd0db6655492199a63e30f788b340":{
      "scriptId":"u14"},
    "5dd88b0f1d4740628cf8ff8749a9a913":{
      "scriptId":"u15"},
    "74377155a6e84eb6afa87ed920435b34":{
      "scriptId":"u16"},
    "148c35990f64441c905efbac17d9e73c":{
      "scriptId":"u17"},
    "7f4bf1624b794a9491251114dd0e5ca5":{
      "scriptId":"u18"},
    "47a4e99616b04566bcfdc2900180b38b":{
      "scriptId":"u19"},
    "15faf501aa754cc0822ced68252b5f8f":{
      "scriptId":"u20"},
    "08a4216d297f4a148b141bbb80380b0f":{
      "scriptId":"u21"},
    "a7b07d34aa3d4151b374585c453e0f02":{
      "scriptId":"u22"},
    "c2b2fb012e9240f397dbb7f139828dce":{
      "scriptId":"u23"},
    "fca59f4631ec4c66a608e343991cd754":{
      "scriptId":"u24"},
    "3f8cf07df06a4f2591be071677a812b7":{
      "scriptId":"u25"},
    "cd6f67ad934047d0a954f6cfc8159f61":{
      "scriptId":"u26"},
    "368ff5559b1e444c952e167dfd9349ee":{
      "scriptId":"u27"},
    "c5e6b3048b3144a8a75e0236d30dcc2c":{
      "scriptId":"u28"},
    "2b4659b510ee4050b39451d97fa02e30":{
      "scriptId":"u29"},
    "13aeaef076bb48418d60896bf4ab8cd5":{
      "scriptId":"u30"},
    "26c2fc9759b942a5aabc7fc9b9218143":{
      "scriptId":"u31"},
    "0466aba4c80b437d81284e24668dfae5":{
      "scriptId":"u32"},
    "09a7cb536b624fee928539e28210185a":{
      "scriptId":"u33"},
    "0d6b3fcad04a4b9ca95b63834f205106":{
      "scriptId":"u34"},
    "226abf69f21540e98d78e7e514b1875b":{
      "scriptId":"u35"},
    "41530a4a967d4d55ada513be9d0f8380":{
      "scriptId":"u36"},
    "eddf2c7873c14747ba1d668d86fd7b55":{
      "scriptId":"u37"},
    "2107c5cfd3f24bf39ccf855f7c3e053e":{
      "scriptId":"u38"},
    "633f31b604fa439998cae00b28c4de8c":{
      "scriptId":"u39"},
    "ebbafb550390497291019a63263ab6e7":{
      "scriptId":"u40"},
    "4f307ab8035e4d45b18bab266b93a19c":{
      "scriptId":"u41"},
    "7d288a369aee4592b6d3befcbd715855":{
      "scriptId":"u42"},
    "5826908d91d546699dbd18704547bc64":{
      "scriptId":"u43"},
    "f0212b0dd2a4467baad9fed228058d04":{
      "scriptId":"u44"},
    "e36439af79fa438586662d955c1bde01":{
      "scriptId":"u45"},
    "742bdc88dd2e4bb897d929f0c1155111":{
      "scriptId":"u46"},
    "5690101644f2479dbf36f94ce325bf08":{
      "scriptId":"u47"},
    "f8c5027acf574c858fb822ccf0d0f1de":{
      "scriptId":"u48"},
    "4ffe350bbe924d6c8cfad573e5909af7":{
      "scriptId":"u49"},
    "53f03e2084f248ffb0dda6d94885ebe0":{
      "scriptId":"u50"},
    "751ffeab1b584d8a8cd3272bbbb600bd":{
      "scriptId":"u51"},
    "895059f4319a47d49a8403c4a2e2916e":{
      "scriptId":"u52"}}});