$axure.loadCurrentPage({
  "url":"支付成功_1.html",
  "generationDate":new Date(1503556105820.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"page"],
  "page":{
    "packageId":"beb87f5fb20246f5bb86f1fadc7253cc",
    "type":"Axure:Page",
    "name":"支付成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"369a765741864e77859e7cb344c6ddcf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c94d045b688f4093a481803d48ae3b30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付成功_1/u0.png"}},
{
          "id":"c1a49097e7fb40d19a11dab138f48c26",
          "label":"返回",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":70,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45ccb1c00c2f42f1ab051096981c5b2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":70,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f120ac4ee648454ab63f440edab4cffd",
          "label":"查看进度",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":10,
              "y":420},
            "size":{
              "width":360,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb2644704f9342cbb1f97c799813b198",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":10,
                  "y":420},
                "size":{
                  "width":360,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 业务办理进度",
                      "target":{
                        "targetType":"page",
                        "url":"业务办理进度.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d649407fdbc4085a1c2c84e307b4bbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":83},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"696439961d424253bbd4875b6ce985ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":83},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}},
{
          "id":"2081080cbbbe4fa183a0210716ab8a32",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":150},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"032ed3a2dd2a445db64be531e4cfa9ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":150},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}},
{
          "id":"9299a7670ca94579997b3aff6268a20f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":217},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f351b912d149407ea37fd4b47e72b6b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":217},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}},
{
          "id":"67fe616e1d504ae29bacf00c97615ab1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":284},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0ef245315bd4b9b8b91f2eaf1f898e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":284},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}},
{
          "id":"734fbac050c3407189523dc36fa23faa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":351},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b9b329edadb48fc92268f8a57d23125",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":351},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "369a765741864e77859e7cb344c6ddcf":{
      "scriptId":"u0"},
    "c94d045b688f4093a481803d48ae3b30":{
      "scriptId":"u1"},
    "c1a49097e7fb40d19a11dab138f48c26":{
      "scriptId":"u2"},
    "45ccb1c00c2f42f1ab051096981c5b2c":{
      "scriptId":"u3"},
    "f120ac4ee648454ab63f440edab4cffd":{
      "scriptId":"u4"},
    "fb2644704f9342cbb1f97c799813b198":{
      "scriptId":"u5"},
    "0d649407fdbc4085a1c2c84e307b4bbf":{
      "scriptId":"u6"},
    "696439961d424253bbd4875b6ce985ec":{
      "scriptId":"u7"},
    "2081080cbbbe4fa183a0210716ab8a32":{
      "scriptId":"u8"},
    "032ed3a2dd2a445db64be531e4cfa9ad":{
      "scriptId":"u9"},
    "9299a7670ca94579997b3aff6268a20f":{
      "scriptId":"u10"},
    "f351b912d149407ea37fd4b47e72b6b9":{
      "scriptId":"u11"},
    "67fe616e1d504ae29bacf00c97615ab1":{
      "scriptId":"u12"},
    "b0ef245315bd4b9b8b91f2eaf1f898e1":{
      "scriptId":"u13"},
    "734fbac050c3407189523dc36fa23faa":{
      "scriptId":"u14"},
    "0b9b329edadb48fc92268f8a57d23125":{
      "scriptId":"u15"}}});