$axure.loadCurrentPage({
  "url":"信息发布.html",
  "generationDate":new Date(1503556106907.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"page"],
  "page":{
    "packageId":"ec68df5f72f044c596b2a49195310f1a",
    "type":"Axure:Page",
    "name":"信息发布",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"72f6bfac215d4591a991815694ed04ac",
          "label":"信息发布",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":677}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"c499b83c73b54080995a8309e90f7f53",
              "label":"路况直播",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5166804c3e6846419ed6e556a7055cbf",
                  "label":"",
                  "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":375,
                      "height":677}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"32d44ec0583b48d19937950f9575d2e2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":375,
                          "height":677}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/信息发布/u1.png"}},
{
                  "id":"57647b77ab0443c586f9e441240458e0",
                  "label":"",
                  "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":-10,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4a9521bb819947eeb2ef101002142390",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":-10,
                          "y":20},
                        "size":{
                          "width":100,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1c0be64ed21a43bebd32a2e289825ccc",
                  "label":"",
                  "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":122,
                      "y":70},
                    "size":{
                      "width":130,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"08b2c4b5ecf74865b7d43b98dd6f0323",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":122,
                          "y":70},
                        "size":{
                          "width":130,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 信息发布 to 突发事件",
                              "panelsToStates":[{
                                  "panelPath":["72f6bfac215d4591a991815694ed04ac"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f5a8c26c9bf74ae49395ddb9a5255967",
                  "label":"",
                  "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":245,
                      "y":60},
                    "size":{
                      "width":130,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"62768702bff14ccd87f5b4ca7a03968e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":245,
                          "y":60},
                        "size":{
                          "width":130,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 信息发布 to 施工公告",
                              "panelsToStates":[{
                                  "panelPath":["72f6bfac215d4591a991815694ed04ac"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"46914b68fe054d0daff94382255c6c0a",
                  "label":"",
                  "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软 Regular', '微软'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCEE0EA,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1E82D0},
                    "location":{
                      "x":299,
                      "y":27},
                    "size":{
                      "width":70,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"015fa64da8bb4851ac2f8d71f0686182",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软 Regular', '微软'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCEE0EA,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1E82D0},
                        "location":{
                          "x":299,
                          "y":27},
                        "size":{
                          "width":70,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 上报",
                              "target":{
                                "targetType":"page",
                                "url":"上报.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/信息发布/u9.png"}}]},
{
              "id":"730c6cb52b114bb3a44cee6e91a37750",
              "label":"突发事件",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8d8a2a919ed74d449024270f3852f0ce",
                  "label":"",
                  "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":375,
                      "height":677}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a8213e72c8554a14add89886898fc6c4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":375,
                          "height":677}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/信息发布/u11.png"}},
{
                  "id":"221a53300acf43fe80ad6be2343dfa52",
                  "label":"",
                  "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":130,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a9677a50fc2d4e7e834f40ce7d705064",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":60},
                        "size":{
                          "width":130,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 信息发布 to 路况直播",
                              "panelsToStates":[{
                                  "panelPath":["72f6bfac215d4591a991815694ed04ac"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a87f58a0dd0c47e2b8cfada38c907080",
                  "label":"",
                  "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":245,
                      "y":60},
                    "size":{
                      "width":130,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f8c98dc3ffb14611832cdfcc70279989",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":245,
                          "y":60},
                        "size":{
                          "width":130,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 信息发布 to 施工公告",
                              "panelsToStates":[{
                                  "panelPath":["72f6bfac215d4591a991815694ed04ac"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f4b695b172284c82ba05d6286db9bb30",
                  "label":"",
                  "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f6dcc4df0a904b42bcaa89906cebc9a2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":20},
                        "size":{
                          "width":100,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d7cb204d037f460fa8a92d498f2c0bb8",
                  "label":"",
                  "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软 Regular', '微软'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCEE0EA,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1E82D2},
                    "location":{
                      "x":299,
                      "y":27},
                    "size":{
                      "width":70,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fd4d482c4dae4d72825974792a5d2369",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软 Regular', '微软'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCEE0EA,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1E82D2},
                        "location":{
                          "x":299,
                          "y":27},
                        "size":{
                          "width":70,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 上报",
                              "target":{
                                "targetType":"page",
                                "url":"上报.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/信息发布/u19.png"}}]},
{
              "id":"d1e08f67a4144eb195e8f93aa458d63a",
              "label":"施工公告",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"97784f6ba5c64be4b8fc17f17a7b5aad",
                  "label":"",
                  "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":375,
                      "height":677}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"caaa160160aa472499d00521670b42fb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":375,
                          "height":677}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/信息发布/u21.png"}},
{
                  "id":"2df9788cdfd6413bb314e65af6de7dd1",
                  "label":"",
                  "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":16},
                    "size":{
                      "width":100,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"71f7009f6d2e483296566c79fe8e342c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":16},
                        "size":{
                          "width":100,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9c5b13431272439aa0bf0211209399c5",
                  "label":"",
                  "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":124,
                      "y":61},
                    "size":{
                      "width":130,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bfcc1ceac63540e894ebf759ff94694a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":124,
                          "y":61},
                        "size":{
                          "width":130,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 信息发布 to 突发事件",
                              "panelsToStates":[{
                                  "panelPath":["72f6bfac215d4591a991815694ed04ac"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7c0dd355eb0344cdb966347e33d7edcf",
                  "label":"",
                  "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":130,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"868f431587c64c2799ce837366b9d372",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":66},
                        "size":{
                          "width":130,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 信息发布 to 路况直播",
                              "panelsToStates":[{
                                  "panelPath":["72f6bfac215d4591a991815694ed04ac"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c39d947d192c4b9ebfe28a44f0948c2d",
                  "label":"",
                  "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软 Regular', '微软'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCEE0EA,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1E82D2},
                    "location":{
                      "x":299,
                      "y":27},
                    "size":{
                      "width":70,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f05fb70ed92b41baa661bcf079a20375",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"72f6bfac215d4591a991815694ed04ac",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软 Regular', '微软'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCEE0EA,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1E82D2},
                        "location":{
                          "x":299,
                          "y":27},
                        "size":{
                          "width":70,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 上报",
                              "target":{
                                "targetType":"page",
                                "url":"上报.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/信息发布/u19.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "72f6bfac215d4591a991815694ed04ac":{
      "scriptId":"u0"},
    "5166804c3e6846419ed6e556a7055cbf":{
      "scriptId":"u1"},
    "32d44ec0583b48d19937950f9575d2e2":{
      "scriptId":"u2"},
    "57647b77ab0443c586f9e441240458e0":{
      "scriptId":"u3"},
    "4a9521bb819947eeb2ef101002142390":{
      "scriptId":"u4"},
    "1c0be64ed21a43bebd32a2e289825ccc":{
      "scriptId":"u5"},
    "08b2c4b5ecf74865b7d43b98dd6f0323":{
      "scriptId":"u6"},
    "f5a8c26c9bf74ae49395ddb9a5255967":{
      "scriptId":"u7"},
    "62768702bff14ccd87f5b4ca7a03968e":{
      "scriptId":"u8"},
    "46914b68fe054d0daff94382255c6c0a":{
      "scriptId":"u9"},
    "015fa64da8bb4851ac2f8d71f0686182":{
      "scriptId":"u10"},
    "8d8a2a919ed74d449024270f3852f0ce":{
      "scriptId":"u11"},
    "a8213e72c8554a14add89886898fc6c4":{
      "scriptId":"u12"},
    "221a53300acf43fe80ad6be2343dfa52":{
      "scriptId":"u13"},
    "a9677a50fc2d4e7e834f40ce7d705064":{
      "scriptId":"u14"},
    "a87f58a0dd0c47e2b8cfada38c907080":{
      "scriptId":"u15"},
    "f8c98dc3ffb14611832cdfcc70279989":{
      "scriptId":"u16"},
    "f4b695b172284c82ba05d6286db9bb30":{
      "scriptId":"u17"},
    "f6dcc4df0a904b42bcaa89906cebc9a2":{
      "scriptId":"u18"},
    "d7cb204d037f460fa8a92d498f2c0bb8":{
      "scriptId":"u19"},
    "fd4d482c4dae4d72825974792a5d2369":{
      "scriptId":"u20"},
    "97784f6ba5c64be4b8fc17f17a7b5aad":{
      "scriptId":"u21"},
    "caaa160160aa472499d00521670b42fb":{
      "scriptId":"u22"},
    "2df9788cdfd6413bb314e65af6de7dd1":{
      "scriptId":"u23"},
    "71f7009f6d2e483296566c79fe8e342c":{
      "scriptId":"u24"},
    "9c5b13431272439aa0bf0211209399c5":{
      "scriptId":"u25"},
    "bfcc1ceac63540e894ebf759ff94694a":{
      "scriptId":"u26"},
    "7c0dd355eb0344cdb966347e33d7edcf":{
      "scriptId":"u27"},
    "868f431587c64c2799ce837366b9d372":{
      "scriptId":"u28"},
    "c39d947d192c4b9ebfe28a44f0948c2d":{
      "scriptId":"u29"},
    "f05fb70ed92b41baa661bcf079a20375":{
      "scriptId":"u30"}}});