$axure.loadCurrentPage({
  "url":"我的路线—编辑点.html",
  "generationDate":new Date(1503556106713.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"page"],
  "page":{
    "packageId":"368f8da2ce164f648088cd92b7b8e816",
    "type":"Axure:Page",
    "name":"我的路线—编辑点",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cdd653f618d843ba8744c528025346f9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a46e5027e3146a7a0d37d76d836f9a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的路线—编辑点/u0.png"}},
{
          "id":"c62315189a75469a9041c4b898d4727b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":75},
            "size":{
              "width":290,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"45a1253b57024294be447231e3030910",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "location":{
              "x":285,
              "y":15},
            "size":{
              "width":90,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec395a66160f403b89fc703e93153411",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "location":{
                  "x":285,
                  "y":15},
                "size":{
                  "width":90,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的路线-确定修改",
                      "target":{
                        "targetType":"page",
                        "url":"我的路线-确定修改.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e180e3125d24d6db3cdfcde0c3916ff",
          "label":"删除",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "location":{
              "x":10,
              "y":120},
            "size":{
              "width":180,
              "height":130},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f63e26eccc1348aba1c3e16bbd0a6c51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "location":{
                  "x":10,
                  "y":120},
                "size":{
                  "width":180,
                  "height":130},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 加号",
                      "objectsToFades":[{
                          "objectPath":["ce024e4855ef4520b9b823650e41c9b2"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce024e4855ef4520b9b823650e41c9b2",
          "label":"加号",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":8,
              "y":120},
            "size":{
              "width":180,
              "height":161},
            "visible":false,
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97dd625b0414462aa439c23bbb09ccda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":8,
                  "y":120},
                "size":{
                  "width":180,
                  "height":161},
                "visible":false,
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 我又出现了",
                      "objectsToFades":[{
                          "objectPath":["dbfdd5498dab478796a216088f9a52f8"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的路线—编辑点/加号_u7.png"}},
{
          "id":"dbfdd5498dab478796a216088f9a52f8",
          "label":"我又出现了",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":10,
              "y":120},
            "size":{
              "width":180,
              "height":133},
            "visible":false,
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7bbbfe94125441baace50a8257bc8b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":10,
                  "y":120},
                "size":{
                  "width":180,
                  "height":133},
                "visible":false,
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的路线—编辑点/我又出现了_u9.png"}},
{
          "id":"e0100422d4d84805855a15c98af0e587",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "location":{
              "x":0,
              "y":20},
            "size":{
              "width":90,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da66ccdf5a404ed18a3debbd390becda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":90,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的路线—添加点",
                      "target":{
                        "targetType":"page",
                        "url":"我的路线—添加点.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"378932d6c3e248bca9a2a02ec836321f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":220},
            "size":{
              "width":300,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de9a270d763c45f59c17deb05f80f2d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":220},
                "size":{
                  "width":300,
                  "height":116}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的路线—编辑点/u13.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "cdd653f618d843ba8744c528025346f9":{
      "scriptId":"u0"},
    "5a46e5027e3146a7a0d37d76d836f9a5":{
      "scriptId":"u1"},
    "c62315189a75469a9041c4b898d4727b":{
      "scriptId":"u2"},
    "45a1253b57024294be447231e3030910":{
      "scriptId":"u3"},
    "ec395a66160f403b89fc703e93153411":{
      "scriptId":"u4"},
    "4e180e3125d24d6db3cdfcde0c3916ff":{
      "scriptId":"u5"},
    "f63e26eccc1348aba1c3e16bbd0a6c51":{
      "scriptId":"u6"},
    "ce024e4855ef4520b9b823650e41c9b2":{
      "scriptId":"u7"},
    "97dd625b0414462aa439c23bbb09ccda":{
      "scriptId":"u8"},
    "dbfdd5498dab478796a216088f9a52f8":{
      "scriptId":"u9"},
    "f7bbbfe94125441baace50a8257bc8b9":{
      "scriptId":"u10"},
    "e0100422d4d84805855a15c98af0e587":{
      "scriptId":"u11"},
    "da66ccdf5a404ed18a3debbd390becda":{
      "scriptId":"u12"},
    "378932d6c3e248bca9a2a02ec836321f":{
      "scriptId":"u13"},
    "de9a270d763c45f59c17deb05f80f2d5":{
      "scriptId":"u14"}}});