$axure.loadCurrentPage({
  "url":"实名认证方案一.html",
  "generationDate":new Date(1503556108570.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"page"],
  "page":{
    "packageId":"6ead2fc415584b1abbf09f7d8cc97985",
    "type":"Axure:Page",
    "name":"实名认证方案一",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d8133625d18c409ea8bd9cf2dba13bab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88aa5d24b0f24a10b7b88580a09a2271",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实名认证方案一/u0.png"}},
{
          "id":"cab8b54445f94550a4e0ed07d47c8ba2",
          "label":"返回",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":20},
            "size":{
              "width":70,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f42da4eb2fdd4658a27497154c634fa2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":70,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f9c568fbc9047ceb2732088a1174362",
          "label":"申请绑定",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":11,
              "y":308},
            "size":{
              "width":360,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d8d482299824d6784162a720da1e7e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":11,
                  "y":308},
                "size":{
                  "width":360,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 录制视频",
                      "target":{
                        "targetType":"page",
                        "url":"录制视频.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35983672681449d09c46e80c1b248b04",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":400,
              "y":98},
            "size":{
              "width":150,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e43ce8e7414a4c479e1a82b9f15f1cc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":400,
                  "y":98},
                "size":{
                  "width":150,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实名认证方案一/u6.png"}},
{
          "id":"7b382633679e4651a5893cf680efd1d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":140},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75341ee3bf5744e8aeefc761ab3128eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":140},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"8c5db78441cb44fd9df144d9564debac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":210},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1616c60a559e41acb502a686bf330e8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":210},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"63ae2dffeafe4d73a7923d9d86f57dd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":570,
              "y":140},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aff23ff059944b8b9823e33060587016",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":570,
                  "y":140},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"711965d043c04b11ac98abea6a552042",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":155},
            "size":{
              "width":20,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/实名认证方案一/u14_end.png",
            "line~":"images/实名认证方案一/u14_line.png"}},
{
          "id":"e46f580551ea45adbe43ae5e0c5f9f85",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":190},
            "size":{
              "width":20,
              "height":10},
            "rotation":"90"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/实名认证方案一/u14_end.png",
            "line~":"images/实名认证方案一/u14_line.png"}},
{
          "id":"bb23ca1c0bc94c7fba495dd8f0318bb1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":225},
            "size":{
              "width":20,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/实名认证方案一/u14_end.png",
            "line~":"images/实名认证方案一/u14_line.png"}},
{
          "id":"25ef2ebe628b4bb69541db0ffabdc6e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":570,
              "y":190},
            "size":{
              "width":130,
              "height":80},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3f0a0526d174584a4be210dd243ef24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":570,
                  "y":190},
                "size":{
                  "width":130,
                  "height":80},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实名认证方案一/u17.png"}},
{
          "id":"0ea4cff133614b53a5e010af3a607ee8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":280},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9267e5f5366443c1a42dc8ac1d1a4a30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":280},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"8dc5c58ca560454089d75881eac76ef0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":255},
            "size":{
              "width":20,
              "height":10},
            "rotation":"90"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/实名认证方案一/u14_end.png",
            "line~":"images/实名认证方案一/u14_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d8133625d18c409ea8bd9cf2dba13bab":{
      "scriptId":"u0"},
    "88aa5d24b0f24a10b7b88580a09a2271":{
      "scriptId":"u1"},
    "cab8b54445f94550a4e0ed07d47c8ba2":{
      "scriptId":"u2"},
    "f42da4eb2fdd4658a27497154c634fa2":{
      "scriptId":"u3"},
    "1f9c568fbc9047ceb2732088a1174362":{
      "scriptId":"u4"},
    "7d8d482299824d6784162a720da1e7e4":{
      "scriptId":"u5"},
    "35983672681449d09c46e80c1b248b04":{
      "scriptId":"u6"},
    "e43ce8e7414a4c479e1a82b9f15f1cc4":{
      "scriptId":"u7"},
    "7b382633679e4651a5893cf680efd1d2":{
      "scriptId":"u8"},
    "75341ee3bf5744e8aeefc761ab3128eb":{
      "scriptId":"u9"},
    "8c5db78441cb44fd9df144d9564debac":{
      "scriptId":"u10"},
    "1616c60a559e41acb502a686bf330e8a":{
      "scriptId":"u11"},
    "63ae2dffeafe4d73a7923d9d86f57dd1":{
      "scriptId":"u12"},
    "aff23ff059944b8b9823e33060587016":{
      "scriptId":"u13"},
    "711965d043c04b11ac98abea6a552042":{
      "scriptId":"u14"},
    "e46f580551ea45adbe43ae5e0c5f9f85":{
      "scriptId":"u15"},
    "bb23ca1c0bc94c7fba495dd8f0318bb1":{
      "scriptId":"u16"},
    "25ef2ebe628b4bb69541db0ffabdc6e9":{
      "scriptId":"u17"},
    "b3f0a0526d174584a4be210dd243ef24":{
      "scriptId":"u18"},
    "0ea4cff133614b53a5e010af3a607ee8":{
      "scriptId":"u19"},
    "9267e5f5366443c1a42dc8ac1d1a4a30":{
      "scriptId":"u20"},
    "8dc5c58ca560454089d75881eac76ef0":{
      "scriptId":"u21"}}});