$axure.loadCurrentPage({
  "url":"路段快照详情2.html",
  "generationDate":new Date(1503556106826.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"page"],
  "page":{
    "packageId":"1cb8ac79f5384f009349afed34d9f101",
    "type":"Axure:Page",
    "name":"路段快照详情2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a529689e4a654583adc2cc86bcc3778b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cfd1a8f7491456e8d85131fa7aec45d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/路段快照详情/u0.png"}},
{
          "id":"0f06a5fc39714fc9b9f035306477ed83",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":-10,
              "y":20},
            "size":{
              "width":90,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13a82e71436e4a9180bfdaf3ce3d191a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":-10,
                  "y":20},
                "size":{
                  "width":90,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的路线-确定修改",
                      "target":{
                        "targetType":"page",
                        "url":"我的路线-确定修改.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37dfcbbed6f343b483f561bb6787f1fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":440,
              "y":272},
            "size":{
              "width":340,
              "height":94}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"710fecf686114270b5d4f6fbac9e961c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":440,
                  "y":272},
                "size":{
                  "width":340,
                  "height":94}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/路段快照详情2/u4.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a529689e4a654583adc2cc86bcc3778b":{
      "scriptId":"u0"},
    "0cfd1a8f7491456e8d85131fa7aec45d":{
      "scriptId":"u1"},
    "0f06a5fc39714fc9b9f035306477ed83":{
      "scriptId":"u2"},
    "13a82e71436e4a9180bfdaf3ce3d191a":{
      "scriptId":"u3"},
    "37dfcbbed6f343b483f561bb6787f1fb":{
      "scriptId":"u4"},
    "710fecf686114270b5d4f6fbac9e961c":{
      "scriptId":"u5"}}});