$axure.loadCurrentPage({
  "url":"审核成功.html",
  "generationDate":new Date(1503556108389.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"page"],
  "page":{
    "packageId":"09c8883595b84fbd8f7bf6fdcd8d26f3",
    "type":"Axure:Page",
    "name":"审核成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2eaa3ce4629144e9abc232a15d8f88ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"523df3acd095468c8c3ce6b2b56b8e3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/审核成功/u0.png"}},
{
          "id":"39b37ec3304e4193bb3e58a34b98c374",
          "label":"返回",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":20},
            "size":{
              "width":70,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6952c70433c4378959cdbb2249fa168",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":70,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 业务办理进度",
                      "target":{
                        "targetType":"page",
                        "url":"业务办理进度.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a811727152c4af9ae92edd159204d61",
          "label":"邮递寄件",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":12,
              "y":475},
            "size":{
              "width":350,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33b14037603b4c7fb29488710b9e5154",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":12,
                  "y":475},
                "size":{
                  "width":350,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 提示,<br>取消,<br>确定",
                      "objectsToFades":[{
                          "objectPath":["546aa82b7e0948cdb158e51287c1f001"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ba5b1e1ad3b344b09b886229dfea2424"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6d981f6ba7514b35ae2790a9f07de04e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"546aa82b7e0948cdb158e51287c1f001",
          "label":"提示",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "size":{
              "width":375,
              "height":667},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21086105206c4b719bab7fc4a447306e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "size":{
                  "width":375,
                  "height":667},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/审核成功/提示_u6.png"}},
{
          "id":"ba5b1e1ad3b344b09b886229dfea2424",
          "label":"取消",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":41,
              "y":608},
            "size":{
              "width":126,
              "height":50},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9db66373365a4c23a53e93e32bda1426",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":41,
                  "y":608},
                "size":{
                  "width":126,
                  "height":50},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 提示,<br>取消,<br>确定",
                      "objectsToFades":[{
                          "objectPath":["546aa82b7e0948cdb158e51287c1f001"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ba5b1e1ad3b344b09b886229dfea2424"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6d981f6ba7514b35ae2790a9f07de04e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d981f6ba7514b35ae2790a9f07de04e",
          "label":"确定",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":207,
              "y":608},
            "size":{
              "width":118,
              "height":50},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f063778726349cb8b5fbfda6d8ce5fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":207,
                  "y":608},
                "size":{
                  "width":118,
                  "height":50},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 制作成功",
                      "target":{
                        "targetType":"page",
                        "url":"制作成功.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97a42997e1f546edb49692f08795c861",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":460,
              "y":130},
            "size":{
              "width":110,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9a3933f64974a52860387cd4ab1f8f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":460,
                  "y":130},
                "size":{
                  "width":110,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我要申诉/u10.png"}},
{
          "id":"e34ecc7963234e3d9f6301b2417c0dbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":460,
              "y":180},
            "size":{
              "width":110,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42dcb416926b444eaf746903570bc7fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":460,
                  "y":180},
                "size":{
                  "width":110,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我要申诉/u10.png"}},
{
          "id":"7cf395d00caa400a871c2f9573e45d42",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":460,
              "y":230},
            "size":{
              "width":110,
              "height":60},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b600fbf5fce4e19a395bf0fad2eed04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":460,
                  "y":230},
                "size":{
                  "width":110,
                  "height":60},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检详情/u12.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2eaa3ce4629144e9abc232a15d8f88ef":{
      "scriptId":"u0"},
    "523df3acd095468c8c3ce6b2b56b8e3b":{
      "scriptId":"u1"},
    "39b37ec3304e4193bb3e58a34b98c374":{
      "scriptId":"u2"},
    "b6952c70433c4378959cdbb2249fa168":{
      "scriptId":"u3"},
    "4a811727152c4af9ae92edd159204d61":{
      "scriptId":"u4"},
    "33b14037603b4c7fb29488710b9e5154":{
      "scriptId":"u5"},
    "546aa82b7e0948cdb158e51287c1f001":{
      "scriptId":"u6"},
    "21086105206c4b719bab7fc4a447306e":{
      "scriptId":"u7"},
    "ba5b1e1ad3b344b09b886229dfea2424":{
      "scriptId":"u8"},
    "9db66373365a4c23a53e93e32bda1426":{
      "scriptId":"u9"},
    "6d981f6ba7514b35ae2790a9f07de04e":{
      "scriptId":"u10"},
    "6f063778726349cb8b5fbfda6d8ce5fe":{
      "scriptId":"u11"},
    "97a42997e1f546edb49692f08795c861":{
      "scriptId":"u12"},
    "a9a3933f64974a52860387cd4ab1f8f8":{
      "scriptId":"u13"},
    "e34ecc7963234e3d9f6301b2417c0dbf":{
      "scriptId":"u14"},
    "42dcb416926b444eaf746903570bc7fe":{
      "scriptId":"u15"},
    "7cf395d00caa400a871c2f9573e45d42":{
      "scriptId":"u16"},
    "9b600fbf5fce4e19a395bf0fad2eed04":{
      "scriptId":"u17"}}});