$axure.loadCurrentPage({
  "url":"路况视频.html",
  "generationDate":new Date(1503556106533.12),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"page"],
  "page":{
    "packageId":"dc419d6ed7ef4ff0b696e76294be912e",
    "type":"Axure:Page",
    "name":"路况视频",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7d0b18d6aca0458cb918d836873a56c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe2dbe24108a495688617854e90745be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/路况视频/u0.png"}},
{
          "id":"084f6ba96a9a4cafb3cf7841dc7a4880",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":-10,
              "y":20},
            "size":{
              "width":100,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa1be51583e1474b95fdd1dcdeef325b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":-10,
                  "y":20},
                "size":{
                  "width":100,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8f73af4027143b3ba3f6a12d6b190e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":122,
              "y":60},
            "size":{
              "width":130,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9595e7f70db49388d0a1d497fe534a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":122,
                  "y":60},
                "size":{
                  "width":130,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f8284f80c194752bb74f679149a982f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":-8,
              "y":60},
            "size":{
              "width":130,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"318637d69fed40878cb5247293f76a62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":-8,
                  "y":60},
                "size":{
                  "width":130,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8469d0a95804e649ad766786fc563a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":140},
            "size":{
              "width":180,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2917eaae12114818b7ee7e5326dc6ba2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":140},
                "size":{
                  "width":180,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a6e07840ae540708cd12b5b15022170",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":189.999984741211,
              "y":140},
            "size":{
              "width":180,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c60fe5050b3f437eba553aaa220752a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":189.999984741211,
                  "y":140},
                "size":{
                  "width":180,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da2c54245162437bb7405892ff1a19b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":310},
            "size":{
              "width":180,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78b8b02fbe7e45bdab332c703609994e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":310},
                "size":{
                  "width":180,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd619de929934fd0bc553a2ca6cad68a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":180,
              "y":310},
            "size":{
              "width":180,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc42741f69bb4d33aac899aa8d0fd895",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":180,
                  "y":310},
                "size":{
                  "width":180,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"489bea359da24aca95eaa829ea278d01",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":10,
              "y":490.000030517578},
            "size":{
              "width":180,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b0f3f6b09384836a898ff9ef7f80fe0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":10,
                  "y":490.000030517578},
                "size":{
                  "width":180,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"983190b6c3d1471fa7d00d2c97cfbe38",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":190,
              "y":490},
            "size":{
              "width":180,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4a2ef687cd14ee0bcddfe1a8167316a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":190,
                  "y":490},
                "size":{
                  "width":180,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7d0b18d6aca0458cb918d836873a56c1":{
      "scriptId":"u0"},
    "fe2dbe24108a495688617854e90745be":{
      "scriptId":"u1"},
    "084f6ba96a9a4cafb3cf7841dc7a4880":{
      "scriptId":"u2"},
    "aa1be51583e1474b95fdd1dcdeef325b":{
      "scriptId":"u3"},
    "f8f73af4027143b3ba3f6a12d6b190e3":{
      "scriptId":"u4"},
    "e9595e7f70db49388d0a1d497fe534a2":{
      "scriptId":"u5"},
    "3f8284f80c194752bb74f679149a982f":{
      "scriptId":"u6"},
    "318637d69fed40878cb5247293f76a62":{
      "scriptId":"u7"},
    "c8469d0a95804e649ad766786fc563a7":{
      "scriptId":"u8"},
    "2917eaae12114818b7ee7e5326dc6ba2":{
      "scriptId":"u9"},
    "8a6e07840ae540708cd12b5b15022170":{
      "scriptId":"u10"},
    "c60fe5050b3f437eba553aaa220752a0":{
      "scriptId":"u11"},
    "da2c54245162437bb7405892ff1a19b5":{
      "scriptId":"u12"},
    "78b8b02fbe7e45bdab332c703609994e":{
      "scriptId":"u13"},
    "fd619de929934fd0bc553a2ca6cad68a":{
      "scriptId":"u14"},
    "dc42741f69bb4d33aac899aa8d0fd895":{
      "scriptId":"u15"},
    "489bea359da24aca95eaa829ea278d01":{
      "scriptId":"u16"},
    "9b0f3f6b09384836a898ff9ef7f80fe0":{
      "scriptId":"u17"},
    "983190b6c3d1471fa7d00d2c97cfbe38":{
      "scriptId":"u18"},
    "f4a2ef687cd14ee0bcddfe1a8167316a":{
      "scriptId":"u19"}}});