$axure.loadCurrentPage({
  "url":"我的路线—准备添加途经点.html",
  "generationDate":new Date(1503556106601.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"page"],
  "page":{
    "packageId":"cd090c67555b44bc9915b7e4eddf398e",
    "type":"Axure:Page",
    "name":"我的路线—准备添加途经点",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6a090e78a0c6476c8ed11c0d84b1911e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba223a50ffd84f6282b1c067690c69f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的路线—准备添加途经点/u0.png"}},
{
          "id":"22805fd8561c47efb707d86d9584ba6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":10,
              "y":130},
            "size":{
              "width":180,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef328dd6aed0482b9d3b74de09923768",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":10,
                  "y":130},
                "size":{
                  "width":180,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 所有路段,<br>选择路段,<br>修饰块",
                      "objectsToFades":[{
                          "objectPath":["64d5012728054a1a80a31923f8774b08"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2ee3539a43244a99ac636c1a00336208"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["12a0e6dc819547b8a5a09a5e2e2abc6f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f784a787244b4fff87e35b7a7c111f1a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":75},
            "size":{
              "width":276,
              "height":34}},
          "adaptiveStyles":{
}},
{
          "id":"16dff3fba22e481292e48ad7e3c5ab56",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":20},
            "size":{
              "width":90,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f883e59ecc764f34b52852942d8b280a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":90,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 值于 page = &quot;1&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"page"},
{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]}]}]}},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 道路查询—展示",
                      "target":{
                        "targetType":"page",
                        "url":"道路查询—展示.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df042d5703e0465788e009a8ca9748ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":190.000015258789,
              "y":130},
            "size":{
              "width":180,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"374222f21be0469bb653daca37dcd8a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":190.000015258789,
                  "y":130},
                "size":{
                  "width":180,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 所有路段,<br>选择路段,<br>修饰块",
                      "objectsToFades":[{
                          "objectPath":["64d5012728054a1a80a31923f8774b08"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2ee3539a43244a99ac636c1a00336208"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["12a0e6dc819547b8a5a09a5e2e2abc6f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ddbbe409f124a7daae0b10c2fcde717",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":15,
              "y":274},
            "size":{
              "width":180,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"644bed42d02e4670a8e2c10bd42c56c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":15,
                  "y":274},
                "size":{
                  "width":180,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 所有路段,<br>选择路段,<br>修饰块",
                      "objectsToFades":[{
                          "objectPath":["64d5012728054a1a80a31923f8774b08"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2ee3539a43244a99ac636c1a00336208"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["12a0e6dc819547b8a5a09a5e2e2abc6f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dadf14cc1e04470a85fd43cc1c1ca0f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":195,
              "y":274},
            "size":{
              "width":180,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f02e0493b154e56824f481ef8368d35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":195,
                  "y":274},
                "size":{
                  "width":180,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 所有路段,<br>选择路段,<br>修饰块",
                      "objectsToFades":[{
                          "objectPath":["64d5012728054a1a80a31923f8774b08"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2ee3539a43244a99ac636c1a00336208"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["12a0e6dc819547b8a5a09a5e2e2abc6f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7810f2b9e50a4a0f9fea0640d1180c7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":420},
            "size":{
              "width":180,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"139fbc1f7ac145969deab2b1b60bff3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":420},
                "size":{
                  "width":180,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 所有路段,<br>选择路段,<br>修饰块",
                      "objectsToFades":[{
                          "objectPath":["64d5012728054a1a80a31923f8774b08"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2ee3539a43244a99ac636c1a00336208"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["12a0e6dc819547b8a5a09a5e2e2abc6f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c57fa0c20b7491e94062cc3a4b22c1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":180,
              "y":420},
            "size":{
              "width":180,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee89aec4203d4fd0a64544d9f6770f8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":180,
                  "y":420},
                "size":{
                  "width":180,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 所有路段,<br>选择路段,<br>修饰块",
                      "objectsToFades":[{
                          "objectPath":["64d5012728054a1a80a31923f8774b08"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2ee3539a43244a99ac636c1a00336208"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["12a0e6dc819547b8a5a09a5e2e2abc6f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dba10da73b774a809fed34d557bfba44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":5,
              "y":564},
            "size":{
              "width":180,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05af3ea222334dcca886db43d534a694",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":5,
                  "y":564},
                "size":{
                  "width":180,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 所有路段,<br>选择路段,<br>修饰块",
                      "objectsToFades":[{
                          "objectPath":["64d5012728054a1a80a31923f8774b08"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2ee3539a43244a99ac636c1a00336208"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["12a0e6dc819547b8a5a09a5e2e2abc6f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9fc40a9b334443cc99c761871a304886",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":185,
              "y":564},
            "size":{
              "width":180,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a57a75e332248da879ff9b810359589",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":185,
                  "y":564},
                "size":{
                  "width":180,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 所有路段,<br>选择路段,<br>修饰块",
                      "objectsToFades":[{
                          "objectPath":["64d5012728054a1a80a31923f8774b08"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2ee3539a43244a99ac636c1a00336208"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["12a0e6dc819547b8a5a09a5e2e2abc6f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64d5012728054a1a80a31923f8774b08",
          "label":"所有路段",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":0,
              "y":122},
            "size":{
              "width":373,
              "height":359},
            "visible":false,
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71c17076abee4a959b01e34af75011d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":0,
                  "y":122},
                "size":{
                  "width":373,
                  "height":359},
                "visible":false,
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的路线—准备添加途经点/所有路段_u21.png"}},
{
          "id":"2ee3539a43244a99ac636c1a00336208",
          "label":"选择路段",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":190,
              "y":173},
            "size":{
              "width":180,
              "height":300},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d09052717050440893a47b1d08c73731",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":190,
                  "y":173},
                "size":{
                  "width":180,
                  "height":300},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的路线—添加点",
                      "target":{
                        "targetType":"page",
                        "url":"我的路线—添加点.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12a0e6dc819547b8a5a09a5e2e2abc6f",
          "label":"修饰块",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "opacity":"0",
            "location":{
              "x":320,
              "y":119},
            "size":{
              "width":50,
              "height":41},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1add511ed27b411797ce730c55b4e724",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "opacity":"0",
                "location":{
                  "x":320,
                  "y":119},
                "size":{
                  "width":50,
                  "height":41},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05dfeba0eb6e42d6bcb7b3d8426616a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":404,
              "y":244},
            "size":{
              "width":236,
              "height":157}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feb123c15aba452eab12e105561e86e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":404,
                  "y":244},
                "size":{
                  "width":236,
                  "height":157}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的路线—准备添加途经点/u27.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "6a090e78a0c6476c8ed11c0d84b1911e":{
      "scriptId":"u0"},
    "ba223a50ffd84f6282b1c067690c69f1":{
      "scriptId":"u1"},
    "22805fd8561c47efb707d86d9584ba6b":{
      "scriptId":"u2"},
    "ef328dd6aed0482b9d3b74de09923768":{
      "scriptId":"u3"},
    "f784a787244b4fff87e35b7a7c111f1a":{
      "scriptId":"u4"},
    "16dff3fba22e481292e48ad7e3c5ab56":{
      "scriptId":"u5"},
    "f883e59ecc764f34b52852942d8b280a":{
      "scriptId":"u6"},
    "df042d5703e0465788e009a8ca9748ae":{
      "scriptId":"u7"},
    "374222f21be0469bb653daca37dcd8a6":{
      "scriptId":"u8"},
    "2ddbbe409f124a7daae0b10c2fcde717":{
      "scriptId":"u9"},
    "644bed42d02e4670a8e2c10bd42c56c8":{
      "scriptId":"u10"},
    "dadf14cc1e04470a85fd43cc1c1ca0f4":{
      "scriptId":"u11"},
    "4f02e0493b154e56824f481ef8368d35":{
      "scriptId":"u12"},
    "7810f2b9e50a4a0f9fea0640d1180c7a":{
      "scriptId":"u13"},
    "139fbc1f7ac145969deab2b1b60bff3a":{
      "scriptId":"u14"},
    "3c57fa0c20b7491e94062cc3a4b22c1e":{
      "scriptId":"u15"},
    "ee89aec4203d4fd0a64544d9f6770f8d":{
      "scriptId":"u16"},
    "dba10da73b774a809fed34d557bfba44":{
      "scriptId":"u17"},
    "05af3ea222334dcca886db43d534a694":{
      "scriptId":"u18"},
    "9fc40a9b334443cc99c761871a304886":{
      "scriptId":"u19"},
    "5a57a75e332248da879ff9b810359589":{
      "scriptId":"u20"},
    "64d5012728054a1a80a31923f8774b08":{
      "scriptId":"u21"},
    "71c17076abee4a959b01e34af75011d1":{
      "scriptId":"u22"},
    "2ee3539a43244a99ac636c1a00336208":{
      "scriptId":"u23"},
    "d09052717050440893a47b1d08c73731":{
      "scriptId":"u24"},
    "12a0e6dc819547b8a5a09a5e2e2abc6f":{
      "scriptId":"u25"},
    "1add511ed27b411797ce730c55b4e724":{
      "scriptId":"u26"},
    "05dfeba0eb6e42d6bcb7b3d8426616a7":{
      "scriptId":"u27"},
    "feb123c15aba452eab12e105561e86e6":{
      "scriptId":"u28"}}});