$axure.loadCurrentPage({
  "url":"照片上传.html",
  "generationDate":new Date(1503556105667.07),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"page"],
  "page":{
    "packageId":"418366f02a2f4e3fb636a6767e6cbe0a",
    "type":"Axure:Page",
    "name":"照片上传",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1<br> (If 值于 page 等于 &quot;14&quot;)",
            "isNewIfGroup":false,
            "condition":{
              "exprType":"binaryOp",
              "op":"==",
              "leftExpr":{
                "exprType":"fcall",
                "functionName":"GetGlobalVariableValue",
                "arguments":[{
                    "exprType":"globalVariableLiteral",
                    "variableName":"page"}]},
              "rightExpr":{
                "exprType":"stringLiteral",
                "value":"14",
                "stos":[]}},
            "actions":[{
                "action":"fadeWidget",
                "description":"显示 流程图,<br>流程图确定,<br>流程图取消",
                "objectsToFades":[{
                    "objectPath":["c8ad9a14cd924533956d30848706541b"],
                    "fadeInfo":{
                      "fadeType":"show",
                      "options":{
                        "showType":"none"}}},
{
                    "objectPath":["948f4d95a27349b0873f0bf85aad860b"],
                    "fadeInfo":{
                      "fadeType":"show",
                      "options":{
                        "showType":"none"}}},
{
                    "objectPath":["6916a649e7a64039bab68237a81b4be0"],
                    "fadeInfo":{
                      "fadeType":"show",
                      "options":{
                        "showType":"none"}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"64f86081e7774d4eb6a4b39a083d9b0b",
          "label":"上传资料",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ce3e112876f457ca239274221726543",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/照片上传/上传资料_u0.png"}},
{
          "id":"2f488101bfd14e21bdb59dc73e13505d",
          "label":"已上传资料",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "size":{
              "width":375,
              "height":667},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c69d1d0956884052835c1e68d821caf7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "size":{
                  "width":375,
                  "height":667},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/照片上传/已上传资料_u2.png"}},
{
          "id":"e0c315a9e25d4cf5824369c0fb43bd3c",
          "label":"提交申请",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":15,
              "y":540},
            "size":{
              "width":355,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c460a615c393438d8522cae12407728d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":15,
                  "y":540},
                "size":{
                  "width":355,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 收件信息填写",
                      "target":{
                        "targetType":"page",
                        "url":"收件信息填写.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6f30612de52497dbc83fb7784c25485",
          "label":"图例",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":155,
              "y":109},
            "size":{
              "width":56,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4aeab00fb584234a321476a5b0379eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":155,
                  "y":109},
                "size":{
                  "width":56,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 图例蒙版,<br>图例图片,<br>图例我知道了",
                      "objectsToFades":[{
                          "objectPath":["8480a79c6c774006aa97f6830e9315cc"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["781fe0ec8aa64cf0ad23287ce41757a7"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ca269e15d0c247949047b82217024e80"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79c5b3cc30d64c17b63fdb6cd3bfd0ad",
          "label":"查看",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":270,
              "y":120},
            "size":{
              "width":49,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fba30ae0a1c4112aa15daac2f360842",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":270,
                  "y":120},
                "size":{
                  "width":49,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 查看蒙版,<br>查看照片",
                      "objectsToFades":[{
                          "objectPath":["1579719d0cd942a5903ad88767cc0169"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b3604b67fa49444d870e546c0373adf7"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2fc95e361c004e0098c241724198cce9",
          "label":"删除",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":319,
              "y":120},
            "size":{
              "width":49,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6edbd026760a432e9bae67a18df6e9c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":319,
                  "y":120},
                "size":{
                  "width":49,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 上传资料",
                      "objectsToFades":[{
                          "objectPath":["64f86081e7774d4eb6a4b39a083d9b0b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 已上传资料",
                      "objectsToFades":[{
                          "objectPath":["2f488101bfd14e21bdb59dc73e13505d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0435670e222e407884c1e0c4cfe2e826",
          "label":"返回",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":70,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff6184c442e9464391905eb0fac5b184",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":70,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 六年免检",
                      "target":{
                        "targetType":"page",
                        "url":"六年免检.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"024cf74519cf481ab9f4b4b406dd3629",
          "label":"上传",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":230,
              "y":120},
            "size":{
              "width":49,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6e5f5cd17274bcd8c5885a811c9ad2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":230,
                  "y":120},
                "size":{
                  "width":49,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 图例我知道了2,<br>图例图片,<br>图例蒙版",
                      "objectsToFades":[{
                          "objectPath":["1ad22e76ca1f43c6a9f38679b49e2797"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["781fe0ec8aa64cf0ad23287ce41757a7"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8480a79c6c774006aa97f6830e9315cc"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07807246e29d4adaa9d7a28545353db6",
          "label":"拍照蒙版",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "opacity":"0.6",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "size":{
              "width":375,
              "height":667},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39b18e9740d34fab93a1530a34f832b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "opacity":"0.6",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "size":{
                  "width":375,
                  "height":667},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/照片上传/拍照蒙版_u16.png"}},
{
          "id":"b9c85b16a2404672a50b22cf3670fe13",
          "label":"拍照",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":0,
              "y":522},
            "size":{
              "width":375,
              "height":145},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28bc156b60964094826f1a62b599a393",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":0,
                  "y":522},
                "size":{
                  "width":375,
                  "height":145},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/照片上传/拍照_u18.png"}},
{
          "id":"3d2241f4b06247fa97b1362bf33d5eca",
          "label":"取消",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":2,
              "y":616},
            "size":{
              "width":370,
              "height":53},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e5e1ed8772b476eb1c5be5243792f5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":2,
                  "y":616},
                "size":{
                  "width":370,
                  "height":53},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 拍照蒙版,<br>拍照,<br>取消",
                      "objectsToFades":[{
                          "objectPath":["07807246e29d4adaa9d7a28545353db6"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b9c85b16a2404672a50b22cf3670fe13"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["3d2241f4b06247fa97b1362bf33d5eca"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 查看,<br>删除,<br>已上传资料",
                      "objectsToFades":[{
                          "objectPath":["79c5b3cc30d64c17b63fdb6cd3bfd0ad"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2fc95e361c004e0098c241724198cce9"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2f488101bfd14e21bdb59dc73e13505d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1579719d0cd942a5903ad88767cc0169",
          "label":"查看蒙版",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "opacity":"0.6",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "size":{
              "width":375,
              "height":667},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23837f9a90da4052b1856d2b6b7ba72b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "opacity":"0.6",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "size":{
                  "width":375,
                  "height":667},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 查看蒙版,<br>查看照片",
                      "objectsToFades":[{
                          "objectPath":["1579719d0cd942a5903ad88767cc0169"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b3604b67fa49444d870e546c0373adf7"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/照片上传/拍照蒙版_u16.png"}},
{
          "id":"b3604b67fa49444d870e546c0373adf7",
          "label":"查看照片",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":0,
              "y":208},
            "size":{
              "width":375,
              "height":222},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c0bb6b239464a5681bc04aba6ecf7c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":0,
                  "y":208},
                "size":{
                  "width":375,
                  "height":222},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 查看蒙版,<br>查看照片",
                      "objectsToFades":[{
                          "objectPath":["1579719d0cd942a5903ad88767cc0169"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b3604b67fa49444d870e546c0373adf7"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/照片上传/查看照片_u24.png"}},
{
          "id":"c8ad9a14cd924533956d30848706541b",
          "label":"流程图",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "size":{
              "width":375,
              "height":667},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a05c783c36524143b1f08a6b1eb221e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "size":{
                  "width":375,
                  "height":667},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/照片上传/流程图_u26.jpg"}},
{
          "id":"2fe56a2adf454ae4891194bbfacfc4d3",
          "label":"细则",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "size":{
              "width":375,
              "height":667},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8919224d1e904db8a4c83f7eb058cb3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "size":{
                  "width":375,
                  "height":667},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/照片上传/细则_u28.png"}},
{
          "id":"948f4d95a27349b0873f0bf85aad860b",
          "label":"流程图确定",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":199,
              "y":532},
            "size":{
              "width":126,
              "height":46},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4167098fe9664ec791ed96b69cd1af45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":199,
                  "y":532},
                "size":{
                  "width":126,
                  "height":46},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 流程图,<br>流程图确定,<br>流程图取消",
                      "objectsToFades":[{
                          "objectPath":["c8ad9a14cd924533956d30848706541b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["948f4d95a27349b0873f0bf85aad860b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6916a649e7a64039bab68237a81b4be0"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 细则,<br>细则确定,<br>细则取消",
                      "objectsToFades":[{
                          "objectPath":["2fe56a2adf454ae4891194bbfacfc4d3"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["76919fff57c14047bfb37e74ba18e62f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["174a0b25cb2047909b7dd49a393e9162"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6916a649e7a64039bab68237a81b4be0",
          "label":"流程图取消",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":55,
              "y":532},
            "size":{
              "width":126,
              "height":46},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31b0daaa09874af0a9313909322d6fb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":55,
                  "y":532},
                "size":{
                  "width":126,
                  "height":46},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 六年免检",
                      "target":{
                        "targetType":"page",
                        "url":"六年免检.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76919fff57c14047bfb37e74ba18e62f",
          "label":"细则确定",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":197,
              "y":480},
            "size":{
              "width":126,
              "height":46},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed44aa1e51794ab08401e8ca000ab6f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":197,
                  "y":480},
                "size":{
                  "width":126,
                  "height":46},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 细则确定,<br>细则取消,<br>细则",
                      "objectsToFades":[{
                          "objectPath":["76919fff57c14047bfb37e74ba18e62f"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["174a0b25cb2047909b7dd49a393e9162"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2fe56a2adf454ae4891194bbfacfc4d3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"174a0b25cb2047909b7dd49a393e9162",
          "label":"细则取消",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":53,
              "y":480},
            "size":{
              "width":126,
              "height":46},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6417cc7dc6e24ff99d8c013b07585722",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":53,
                  "y":480},
                "size":{
                  "width":126,
                  "height":46},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 六年免检",
                      "target":{
                        "targetType":"page",
                        "url":"六年免检.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8480a79c6c774006aa97f6830e9315cc",
          "label":"图例蒙版",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "opacity":"0.6",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "size":{
              "width":375,
              "height":667},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f6457b28a0748e4ad2157bdd9f3baf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "opacity":"0.6",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "size":{
                  "width":375,
                  "height":667},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/照片上传/拍照蒙版_u16.png"}},
{
          "id":"781fe0ec8aa64cf0ad23287ce41757a7",
          "label":"图例图片",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":18,
              "y":188},
            "size":{
              "width":340,
              "height":290},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3516cbb67dee4138a7929b265c27dc1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":18,
                  "y":188},
                "size":{
                  "width":340,
                  "height":290},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/照片上传/图例图片_u40.png"}},
{
          "id":"ca269e15d0c247949047b82217024e80",
          "label":"图例我知道了",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":31,
              "y":428},
            "size":{
              "width":307,
              "height":48},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d45f31ea3ae46de896e5eb7513acc49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":31,
                  "y":428},
                "size":{
                  "width":307,
                  "height":48},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 图例蒙版,<br>图例图片,<br>图例我知道了",
                      "objectsToFades":[{
                          "objectPath":["8480a79c6c774006aa97f6830e9315cc"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["781fe0ec8aa64cf0ad23287ce41757a7"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ca269e15d0c247949047b82217024e80"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ad22e76ca1f43c6a9f38679b49e2797",
          "label":"图例我知道了2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":26,
              "y":430},
            "size":{
              "width":307,
              "height":48},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0be837234d264f04977f36884f0217ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":26,
                  "y":430},
                "size":{
                  "width":307,
                  "height":48},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 图例蒙版,<br>图例图片,<br>图例我知道了2,<br>图例我知道了",
                      "objectsToFades":[{
                          "objectPath":["8480a79c6c774006aa97f6830e9315cc"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["781fe0ec8aa64cf0ad23287ce41757a7"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["1ad22e76ca1f43c6a9f38679b49e2797"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ca269e15d0c247949047b82217024e80"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 取消,<br>拍照,<br>拍照蒙版",
                      "objectsToFades":[{
                          "objectPath":["3d2241f4b06247fa97b1362bf33d5eca"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b9c85b16a2404672a50b22cf3670fe13"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["07807246e29d4adaa9d7a28545353db6"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f872e1fd5c514ab19399a253f338c588",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":83},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b1742326cd341ec97277016ee7746b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":83},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}},
{
          "id":"7382d5f4e9ea458697a8f4c7ebc7b23c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":150},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4e5dee33c63488bb70f8b8056fa8025",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":150},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}},
{
          "id":"5e4bdaa3957e4488b5003fb253257005",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":217},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9588b2b22d1048aa8c6a462f7150c227",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":217},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}},
{
          "id":"89b32fa183f84f98a1b11904503328eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":284},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02d229965ac74e27b1732cd1675c4be1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":284},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}},
{
          "id":"e83920779bb840e4ad86ed213afbcc03",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":351},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0196f62e4334ce2a8f37631ee8caf7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":351},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "64f86081e7774d4eb6a4b39a083d9b0b":{
      "scriptId":"u0"},
    "6ce3e112876f457ca239274221726543":{
      "scriptId":"u1"},
    "2f488101bfd14e21bdb59dc73e13505d":{
      "scriptId":"u2"},
    "c69d1d0956884052835c1e68d821caf7":{
      "scriptId":"u3"},
    "e0c315a9e25d4cf5824369c0fb43bd3c":{
      "scriptId":"u4"},
    "c460a615c393438d8522cae12407728d":{
      "scriptId":"u5"},
    "f6f30612de52497dbc83fb7784c25485":{
      "scriptId":"u6"},
    "e4aeab00fb584234a321476a5b0379eb":{
      "scriptId":"u7"},
    "79c5b3cc30d64c17b63fdb6cd3bfd0ad":{
      "scriptId":"u8"},
    "0fba30ae0a1c4112aa15daac2f360842":{
      "scriptId":"u9"},
    "2fc95e361c004e0098c241724198cce9":{
      "scriptId":"u10"},
    "6edbd026760a432e9bae67a18df6e9c4":{
      "scriptId":"u11"},
    "0435670e222e407884c1e0c4cfe2e826":{
      "scriptId":"u12"},
    "ff6184c442e9464391905eb0fac5b184":{
      "scriptId":"u13"},
    "024cf74519cf481ab9f4b4b406dd3629":{
      "scriptId":"u14"},
    "d6e5f5cd17274bcd8c5885a811c9ad2e":{
      "scriptId":"u15"},
    "07807246e29d4adaa9d7a28545353db6":{
      "scriptId":"u16"},
    "39b18e9740d34fab93a1530a34f832b4":{
      "scriptId":"u17"},
    "b9c85b16a2404672a50b22cf3670fe13":{
      "scriptId":"u18"},
    "28bc156b60964094826f1a62b599a393":{
      "scriptId":"u19"},
    "3d2241f4b06247fa97b1362bf33d5eca":{
      "scriptId":"u20"},
    "7e5e1ed8772b476eb1c5be5243792f5e":{
      "scriptId":"u21"},
    "1579719d0cd942a5903ad88767cc0169":{
      "scriptId":"u22"},
    "23837f9a90da4052b1856d2b6b7ba72b":{
      "scriptId":"u23"},
    "b3604b67fa49444d870e546c0373adf7":{
      "scriptId":"u24"},
    "1c0bb6b239464a5681bc04aba6ecf7c2":{
      "scriptId":"u25"},
    "c8ad9a14cd924533956d30848706541b":{
      "scriptId":"u26"},
    "a05c783c36524143b1f08a6b1eb221e3":{
      "scriptId":"u27"},
    "2fe56a2adf454ae4891194bbfacfc4d3":{
      "scriptId":"u28"},
    "8919224d1e904db8a4c83f7eb058cb3f":{
      "scriptId":"u29"},
    "948f4d95a27349b0873f0bf85aad860b":{
      "scriptId":"u30"},
    "4167098fe9664ec791ed96b69cd1af45":{
      "scriptId":"u31"},
    "6916a649e7a64039bab68237a81b4be0":{
      "scriptId":"u32"},
    "31b0daaa09874af0a9313909322d6fb3":{
      "scriptId":"u33"},
    "76919fff57c14047bfb37e74ba18e62f":{
      "scriptId":"u34"},
    "ed44aa1e51794ab08401e8ca000ab6f3":{
      "scriptId":"u35"},
    "174a0b25cb2047909b7dd49a393e9162":{
      "scriptId":"u36"},
    "6417cc7dc6e24ff99d8c013b07585722":{
      "scriptId":"u37"},
    "8480a79c6c774006aa97f6830e9315cc":{
      "scriptId":"u38"},
    "6f6457b28a0748e4ad2157bdd9f3baf9":{
      "scriptId":"u39"},
    "781fe0ec8aa64cf0ad23287ce41757a7":{
      "scriptId":"u40"},
    "3516cbb67dee4138a7929b265c27dc1a":{
      "scriptId":"u41"},
    "ca269e15d0c247949047b82217024e80":{
      "scriptId":"u42"},
    "5d45f31ea3ae46de896e5eb7513acc49":{
      "scriptId":"u43"},
    "1ad22e76ca1f43c6a9f38679b49e2797":{
      "scriptId":"u44"},
    "0be837234d264f04977f36884f0217ca":{
      "scriptId":"u45"},
    "f872e1fd5c514ab19399a253f338c588":{
      "scriptId":"u46"},
    "9b1742326cd341ec97277016ee7746b9":{
      "scriptId":"u47"},
    "7382d5f4e9ea458697a8f4c7ebc7b23c":{
      "scriptId":"u48"},
    "b4e5dee33c63488bb70f8b8056fa8025":{
      "scriptId":"u49"},
    "5e4bdaa3957e4488b5003fb253257005":{
      "scriptId":"u50"},
    "9588b2b22d1048aa8c6a462f7150c227":{
      "scriptId":"u51"},
    "89b32fa183f84f98a1b11904503328eb":{
      "scriptId":"u52"},
    "02d229965ac74e27b1732cd1675c4be1":{
      "scriptId":"u53"},
    "e83920779bb840e4ad86ed213afbcc03":{
      "scriptId":"u54"},
    "c0196f62e4334ce2a8f37631ee8caf7d":{
      "scriptId":"u55"}}});