$axure.loadCurrentPage({
  "url":"我的路线—完成展开.html",
  "generationDate":new Date(1503556106797.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"page"],
  "page":{
    "packageId":"51fad620351d43ecbf5906f83e0f73df",
    "type":"Axure:Page",
    "name":"我的路线—完成展开",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9a6479d9d9ce4e4b851f70aa61e881fe",
          "label":"我的路线",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":677}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"4176b9d8578343e98baa4cc7a7df8211",
              "label":"完成状态",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d1f97703bd5348268c3a2130d84883a9",
                  "label":"",
                  "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":375,
                      "height":667}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"58cb9464293d4103b4acc67ae07754f9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":375,
                          "height":667}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的路线—完成展开/u1.png"}},
{
                  "id":"8e893bfffef9402bb7800031eed11bae",
                  "label":"",
                  "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":330,
                      "y":20},
                    "size":{
                      "width":45,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"95daed41114d41c4a8a2ccecf20eef3a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":330,
                          "y":20},
                        "size":{
                          "width":45,
                          "height":45},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 我的路线 to 编辑状态",
                              "panelsToStates":[{
                                  "panelPath":["9a6479d9d9ce4e4b851f70aa61e881fe"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3f5b6271e558486e80757ce0cbcba5b3",
                  "label":"",
                  "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":5,
                      "y":120},
                    "size":{
                      "width":175,
                      "height":130},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"edfd00899371458bb21b0873a03ea27b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":5,
                          "y":120},
                        "size":{
                          "width":175,
                          "height":130},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 路段快照详情2",
                              "target":{
                                "targetType":"page",
                                "url":"路段快照详情2.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f90900f6ebd1430a88a109b2a207fe96",
                  "label":"",
                  "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":190,
                      "y":120},
                    "size":{
                      "width":175,
                      "height":130},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bcef0dec5ddb43c1b5dcc7fe20f4c446",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":190,
                          "y":120},
                        "size":{
                          "width":175,
                          "height":130},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 路段快照详情2",
                              "target":{
                                "targetType":"page",
                                "url":"路段快照详情2.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7eb4cb067ee34afc96d2478a596a9ae3",
                  "label":"",
                  "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":5,
                      "y":290},
                    "size":{
                      "width":175,
                      "height":130},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e19c0e53d07a4fbaa25059d56ef5eff9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":5,
                          "y":290},
                        "size":{
                          "width":175,
                          "height":130},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 路段快照详情2",
                              "target":{
                                "targetType":"page",
                                "url":"路段快照详情2.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"af1c44ef69314fbb86516c71c1562851",
              "label":"编辑状态",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1ede8a2928204c4c8a961b7b1c722b3b",
                  "label":"",
                  "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":375,
                      "height":667}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"385dc0b3b07645f98da68f1b5fc05939",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":375,
                          "height":667}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的路线—完成展开/u11.png"}},
{
                  "id":"e5728b8eea3143b8ad1d620dbfc2d004",
                  "label":"",
                  "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":295,
                      "y":20},
                    "size":{
                      "width":80,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7f1926eda879409e8da4a651dd4d7271",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":295,
                          "y":20},
                        "size":{
                          "width":80,
                          "height":45},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 我的路线 to 完成状态",
                              "panelsToStates":[{
                                  "panelPath":["9a6479d9d9ce4e4b851f70aa61e881fe"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1cf0bb1f6a70488894cdc75b6d4b5863",
                  "label":"",
                  "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":86,
                      "y":74},
                    "size":{
                      "width":282,
                      "height":35}},
                  "adaptiveStyles":{
}},
{
                  "id":"c45f2d2d95134c399ff65d4fb16e7d87",
                  "label":"加号1",
                  "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":10,
                      "y":119},
                    "size":{
                      "width":170,
                      "height":131},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4a81d1b97dd845fba15c7178c1c87816",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":10,
                          "y":119},
                        "size":{
                          "width":170,
                          "height":131},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 加号1",
                              "objectsToFades":[{
                                  "objectPath":["a97c1d0041654c5fa0f044684c24bf41"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7f6740ea9e8b4dd1be7d199442cc1469",
                  "label":"加号2",
                  "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":199,
                      "y":119},
                    "size":{
                      "width":170,
                      "height":131},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"32955c74c38a4a8f8d9522004980973e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":199,
                          "y":119},
                        "size":{
                          "width":170,
                          "height":131},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 加号2",
                              "objectsToFades":[{
                                  "objectPath":["f931b4e887bb4aeea90affeb3cd42270"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"14e1c80ac0954fedb98e103050323147",
                  "label":"加号3",
                  "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":10,
                      "y":284},
                    "size":{
                      "width":170,
                      "height":131},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"422d92f67e0248a9b1452fab59028f94",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":10,
                          "y":284},
                        "size":{
                          "width":170,
                          "height":131},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 加号3",
                              "objectsToFades":[{
                                  "objectPath":["23da06c5c8f542538ea33ad9a40348ba"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a97c1d0041654c5fa0f044684c24bf41",
                  "label":"加号1",
                  "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":10,
                      "y":117},
                    "size":{
                      "width":179,
                      "height":133},
                    "visible":false,
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"71e4b37e11cb4022b58d46e089f92690",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":10,
                          "y":117},
                        "size":{
                          "width":179,
                          "height":133},
                        "visible":false,
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 我的路线—准备添加途经点",
                              "target":{
                                "targetType":"page",
                                "url":"我的路线—准备添加途经点.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/我的路线—完成展开/加号1_u22.png"}},
{
                  "id":"23da06c5c8f542538ea33ad9a40348ba",
                  "label":"加号3",
                  "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":6,
                      "y":284},
                    "size":{
                      "width":179,
                      "height":133},
                    "visible":false,
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eafd299e4bd3443f827565f2872bf8de",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":6,
                          "y":284},
                        "size":{
                          "width":179,
                          "height":133},
                        "visible":false,
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的路线—完成展开/加号1_u22.png"}},
{
                  "id":"f931b4e887bb4aeea90affeb3cd42270",
                  "label":"加号2",
                  "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":190,
                      "y":119},
                    "size":{
                      "width":179,
                      "height":133},
                    "visible":false,
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"02e144613c8442a4a2b9d7b5a49a1c15",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9a6479d9d9ce4e4b851f70aa61e881fe",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":190,
                          "y":119},
                        "size":{
                          "width":179,
                          "height":133},
                        "visible":false,
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的路线—完成展开/加号1_u22.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "9a6479d9d9ce4e4b851f70aa61e881fe":{
      "scriptId":"u0"},
    "d1f97703bd5348268c3a2130d84883a9":{
      "scriptId":"u1"},
    "58cb9464293d4103b4acc67ae07754f9":{
      "scriptId":"u2"},
    "8e893bfffef9402bb7800031eed11bae":{
      "scriptId":"u3"},
    "95daed41114d41c4a8a2ccecf20eef3a":{
      "scriptId":"u4"},
    "3f5b6271e558486e80757ce0cbcba5b3":{
      "scriptId":"u5"},
    "edfd00899371458bb21b0873a03ea27b":{
      "scriptId":"u6"},
    "f90900f6ebd1430a88a109b2a207fe96":{
      "scriptId":"u7"},
    "bcef0dec5ddb43c1b5dcc7fe20f4c446":{
      "scriptId":"u8"},
    "7eb4cb067ee34afc96d2478a596a9ae3":{
      "scriptId":"u9"},
    "e19c0e53d07a4fbaa25059d56ef5eff9":{
      "scriptId":"u10"},
    "1ede8a2928204c4c8a961b7b1c722b3b":{
      "scriptId":"u11"},
    "385dc0b3b07645f98da68f1b5fc05939":{
      "scriptId":"u12"},
    "e5728b8eea3143b8ad1d620dbfc2d004":{
      "scriptId":"u13"},
    "7f1926eda879409e8da4a651dd4d7271":{
      "scriptId":"u14"},
    "1cf0bb1f6a70488894cdc75b6d4b5863":{
      "scriptId":"u15"},
    "c45f2d2d95134c399ff65d4fb16e7d87":{
      "scriptId":"u16"},
    "4a81d1b97dd845fba15c7178c1c87816":{
      "scriptId":"u17"},
    "7f6740ea9e8b4dd1be7d199442cc1469":{
      "scriptId":"u18"},
    "32955c74c38a4a8f8d9522004980973e":{
      "scriptId":"u19"},
    "14e1c80ac0954fedb98e103050323147":{
      "scriptId":"u20"},
    "422d92f67e0248a9b1452fab59028f94":{
      "scriptId":"u21"},
    "a97c1d0041654c5fa0f044684c24bf41":{
      "scriptId":"u22"},
    "71e4b37e11cb4022b58d46e089f92690":{
      "scriptId":"u23"},
    "23da06c5c8f542538ea33ad9a40348ba":{
      "scriptId":"u24"},
    "eafd299e4bd3443f827565f2872bf8de":{
      "scriptId":"u25"},
    "f931b4e887bb4aeea90affeb3cd42270":{
      "scriptId":"u26"},
    "02e144613c8442a4a2b9d7b5a49a1c15":{
      "scriptId":"u27"}}});