$axure.loadCurrentPage({
  "url":"驾驶人交通违法查询.html",
  "generationDate":new Date(1503556105968.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"page"],
  "page":{
    "packageId":"f26ebd11f2854b7aaca483629cde415b",
    "type":"Axure:Page",
    "name":"驾驶人交通违法查询",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c083df118f97404281c0abf837bf1f93",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f3b17527b674719b309705a4b8c34cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/驾驶人交通违法查询/u0.png"}},
{
          "id":"00f0f879c77d4acba597d60ec908e5a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":4,
              "y":271},
            "size":{
              "width":360,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c8a4812c81c4ba9a31333b9f24d2ee0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":4,
                  "y":271},
                "size":{
                  "width":360,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"有违法",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 驾驶人违法查询结果—有违法",
                      "target":{
                        "targetType":"page",
                        "url":"驾驶人违法查询结果—有违法.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"无违法",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 驾驶人违法查询—无违法",
                      "target":{
                        "targetType":"page",
                        "url":"驾驶人违法查询—无违法.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c90d9c9aef8473bb065a73188458ae8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":-10,
              "y":20},
            "size":{
              "width":90,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"530d061eb9284eab957c376d0881c34d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":-10,
                  "y":20},
                "size":{
                  "width":90,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18918c4eb50f4237a741d1aa438dc1fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":83},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c9b68d0467b4df38eac5bbfcc951c78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":83},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}},
{
          "id":"0153010f7b5b48bb8e103799d9268d07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":420,
              "y":150},
            "size":{
              "width":130,
              "height":57},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7464954d4a1c4903862ae9bea488059b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":420,
                  "y":150},
                "size":{
                  "width":130,
                  "height":57},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/六年免检/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c083df118f97404281c0abf837bf1f93":{
      "scriptId":"u0"},
    "3f3b17527b674719b309705a4b8c34cd":{
      "scriptId":"u1"},
    "00f0f879c77d4acba597d60ec908e5a4":{
      "scriptId":"u2"},
    "5c8a4812c81c4ba9a31333b9f24d2ee0":{
      "scriptId":"u3"},
    "5c90d9c9aef8473bb065a73188458ae8":{
      "scriptId":"u4"},
    "530d061eb9284eab957c376d0881c34d":{
      "scriptId":"u5"},
    "18918c4eb50f4237a741d1aa438dc1fa":{
      "scriptId":"u6"},
    "4c9b68d0467b4df38eac5bbfcc951c78":{
      "scriptId":"u7"},
    "0153010f7b5b48bb8e103799d9268d07":{
      "scriptId":"u8"},
    "7464954d4a1c4903862ae9bea488059b":{
      "scriptId":"u9"}}});