$axure.loadCurrentPage({
  "url":"实名认证方案二.html",
  "generationDate":new Date(1503556108792.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"page"],
  "page":{
    "packageId":"a9848c1d70794652bae509c0a05b15e3",
    "type":"Axure:Page",
    "name":"实名认证方案二",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fd0c405ee8854aef801436d9b0087cae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"252b468a221742288220fa5cc413c12e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实名认证方案一/u0.png"}},
{
          "id":"29afa4cfdae044dfbd3b63d6b803f461",
          "label":"返回",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":20},
            "size":{
              "width":70,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efe9652019a3490fbdb96088f23da64b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":70,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49007b9cbfea4e56af1c9c726b440644",
          "label":"申请绑定",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":8,
              "y":308},
            "size":{
              "width":360,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25965822de9c461d950920bc1f069014",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":8,
                  "y":308},
                "size":{
                  "width":360,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 证件上传",
                      "target":{
                        "targetType":"page",
                        "url":"证件上传.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0262a6cd81641b6bc629d43eb9135b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":400,
              "y":98},
            "size":{
              "width":150,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70081bdbb8aa4ff788de2fa25b804ff6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":400,
                  "y":98},
                "size":{
                  "width":150,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实名认证方案一/u6.png"}},
{
          "id":"cbf6492849744cb3861a2754707703ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":140},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"818466d9cb6946908f7a6a7c72a08e10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":140},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"517d919bb9694b34b8cc059756629860",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":210},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caea339fcb2a4b228d8c992b25dae600",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":210},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"12f734468d344da1bfee8024a231a128",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":570,
              "y":140},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55c2aed155a84dbdb77228fe1801061e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":570,
                  "y":140},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"b22fff66d55545beacaf9f36c8f80609",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":155},
            "size":{
              "width":20,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/实名认证方案一/u14_end.png",
            "line~":"images/实名认证方案一/u14_line.png"}},
{
          "id":"27f6849fe06b4df6b5db0fa4e9b0960c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":190},
            "size":{
              "width":20,
              "height":10},
            "rotation":"90"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/实名认证方案一/u14_end.png",
            "line~":"images/实名认证方案一/u14_line.png"}},
{
          "id":"e1cc8a1bee934e55b2d62a2e7f17f2e5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":225},
            "size":{
              "width":20,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/实名认证方案一/u14_end.png",
            "line~":"images/实名认证方案一/u14_line.png"}},
{
          "id":"c9fb64f6016c47ce8ed9116b5a3962a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":570,
              "y":190},
            "size":{
              "width":130,
              "height":80},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32a9dbbd460a4582a264fe45c7163e93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":570,
                  "y":190},
                "size":{
                  "width":130,
                  "height":80},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实名认证方案一/u17.png"}},
{
          "id":"c670027ba97e4ebe8ce94929825f224a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":410,
              "y":280},
            "size":{
              "width":130,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc595af0f95d484dba30279bfd976da0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":410,
                  "y":280},
                "size":{
                  "width":130,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快撤快赔首页/u10.png"}},
{
          "id":"3a2dd431a9614555bae74afe764251cf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":255},
            "size":{
              "width":20,
              "height":10},
            "rotation":"90"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/实名认证方案一/u14_end.png",
            "line~":"images/实名认证方案一/u14_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "fd0c405ee8854aef801436d9b0087cae":{
      "scriptId":"u0"},
    "252b468a221742288220fa5cc413c12e":{
      "scriptId":"u1"},
    "29afa4cfdae044dfbd3b63d6b803f461":{
      "scriptId":"u2"},
    "efe9652019a3490fbdb96088f23da64b":{
      "scriptId":"u3"},
    "49007b9cbfea4e56af1c9c726b440644":{
      "scriptId":"u4"},
    "25965822de9c461d950920bc1f069014":{
      "scriptId":"u5"},
    "e0262a6cd81641b6bc629d43eb9135b7":{
      "scriptId":"u6"},
    "70081bdbb8aa4ff788de2fa25b804ff6":{
      "scriptId":"u7"},
    "cbf6492849744cb3861a2754707703ce":{
      "scriptId":"u8"},
    "818466d9cb6946908f7a6a7c72a08e10":{
      "scriptId":"u9"},
    "517d919bb9694b34b8cc059756629860":{
      "scriptId":"u10"},
    "caea339fcb2a4b228d8c992b25dae600":{
      "scriptId":"u11"},
    "12f734468d344da1bfee8024a231a128":{
      "scriptId":"u12"},
    "55c2aed155a84dbdb77228fe1801061e":{
      "scriptId":"u13"},
    "b22fff66d55545beacaf9f36c8f80609":{
      "scriptId":"u14"},
    "27f6849fe06b4df6b5db0fa4e9b0960c":{
      "scriptId":"u15"},
    "e1cc8a1bee934e55b2d62a2e7f17f2e5":{
      "scriptId":"u16"},
    "c9fb64f6016c47ce8ed9116b5a3962a5":{
      "scriptId":"u17"},
    "32a9dbbd460a4582a264fe45c7163e93":{
      "scriptId":"u18"},
    "c670027ba97e4ebe8ce94929825f224a":{
      "scriptId":"u19"},
    "cc595af0f95d484dba30279bfd976da0":{
      "scriptId":"u20"},
    "3a2dd431a9614555bae74afe764251cf":{
      "scriptId":"u21"}}});