$axure.loadCurrentPage({
  "url":"路况简图.html",
  "generationDate":new Date(1503556107052.15),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"page"],
  "page":{
    "packageId":"56481e6a5f2d43a09918379a09b95f25",
    "type":"Axure:Page",
    "name":"路况简图",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b2d30f7da40244478288fd559917fed3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6e977bd15ef45c2a151a6610f90ec69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/路况简图/u0.png"}},
{
          "id":"7218e15fd44e4e9db71a58351a6c90e4",
          "label":"株洲全市选择黑板",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "opacity":"0.6",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":0,
              "y":346},
            "size":{
              "width":375,
              "height":321},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb646da71e854c96b63f798c55577906",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "opacity":"0.6",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":0,
                  "y":346},
                "size":{
                  "width":375,
                  "height":321},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/路况简图/株洲全市选择黑板_u2.png"}},
{
          "id":"b8cdef99dcbe4896abedb18c3f345c90",
          "label":"天元区",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":0,
              "y":66},
            "size":{
              "width":374,
              "height":601},
            "visible":false,
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a32c1b5dcaf0468983d6166dad3ea824",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":374,
                  "height":601},
                "visible":false,
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/路况简图/天元区_u4.png"}},
{
          "id":"01c721bc7a3d47ccae230da6e2d65ff7",
          "label":"天元区选择版",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":0,
              "y":64},
            "size":{
              "width":375,
              "height":602},
            "visible":false,
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3514d87df0c049ee9c849280663345d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":0,
                  "y":64},
                "size":{
                  "width":375,
                  "height":602},
                "visible":false,
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/路况简图/天元区选择版_u6.png"}},
{
          "id":"3466a1cd175f430584553c10b1edf33d",
          "label":"株洲全市选择版",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":0,
              "y":113},
            "size":{
              "width":375,
              "height":235},
            "visible":false,
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd0a516c71eb4d2c8e672d05c642c991",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":0,
                  "y":113},
                "size":{
                  "width":375,
                  "height":235},
                "visible":false,
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/路况简图/株洲全市选择版_u8.png"}},
{
          "id":"85a8f99d46d14886a1905f04baf566fb",
          "label":"株洲市选择栏",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":64},
            "size":{
              "width":380,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04bf35a54e144fcb934a4e5a73e39244",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":64},
                "size":{
                  "width":380,
                  "height":56},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 株洲全市选择版,<br>株洲全市选择黑板,<br>选择株洲全市,<br>选择天元区",
                      "objectsToFades":[{
                          "objectPath":["3466a1cd175f430584553c10b1edf33d"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["7218e15fd44e4e9db71a58351a6c90e4"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["983d5598f59344a09d3542132e03411c"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["52b05746b2b9403385f0ef563e03a2d7"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69cb02fc45f34f3b9f017d05a29b8c4f",
          "label":"天元区选择栏",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":64},
            "size":{
              "width":380,
              "height":56},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a33eaeb54fa445bac7c2f62ec8e3a21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":64},
                "size":{
                  "width":380,
                  "height":56},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 选择天元区,<br>选择株洲全市,<br>天元区选择版",
                      "objectsToFades":[{
                          "objectPath":["52b05746b2b9403385f0ef563e03a2d7"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["983d5598f59344a09d3542132e03411c"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["01c721bc7a3d47ccae230da6e2d65ff7"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86333555d6344830aa2b49af1e567d03",
          "label":"返回键",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":20},
            "size":{
              "width":70,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"289a59966198463c899b1f05f5bb3703",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":70,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52b05746b2b9403385f0ef563e03a2d7",
          "label":"选择天元区",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":156},
            "size":{
              "width":380,
              "height":40},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f81604a2ed04c1aabed183e7754aa82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":156},
                "size":{
                  "width":380,
                  "height":40},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 选择天元区,<br>株洲全市选择黑板,<br>株洲全市选择版,<br>选择株洲全市,<br>天元区选择版",
                      "objectsToFades":[{
                          "objectPath":["52b05746b2b9403385f0ef563e03a2d7"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["7218e15fd44e4e9db71a58351a6c90e4"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["3466a1cd175f430584553c10b1edf33d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["983d5598f59344a09d3542132e03411c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["01c721bc7a3d47ccae230da6e2d65ff7"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 天元区,<br>天元区选择栏",
                      "objectsToFades":[{
                          "objectPath":["b8cdef99dcbe4896abedb18c3f345c90"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["69cb02fc45f34f3b9f017d05a29b8c4f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"983d5598f59344a09d3542132e03411c",
          "label":"选择株洲全市",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":116},
            "size":{
              "width":380,
              "height":37},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bab2ee702594c528b678535675229db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":116},
                "size":{
                  "width":380,
                  "height":37},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 选择株洲全市,<br>株洲全市选择黑板,<br>株洲全市选择版,<br>选择天元区,<br>天元区选择栏,<br>天元区,<br>天元区选择版",
                      "objectsToFades":[{
                          "objectPath":["983d5598f59344a09d3542132e03411c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["7218e15fd44e4e9db71a58351a6c90e4"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["3466a1cd175f430584553c10b1edf33d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["52b05746b2b9403385f0ef563e03a2d7"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["69cb02fc45f34f3b9f017d05a29b8c4f"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b8cdef99dcbe4896abedb18c3f345c90"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["01c721bc7a3d47ccae230da6e2d65ff7"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "b2d30f7da40244478288fd559917fed3":{
      "scriptId":"u0"},
    "e6e977bd15ef45c2a151a6610f90ec69":{
      "scriptId":"u1"},
    "7218e15fd44e4e9db71a58351a6c90e4":{
      "scriptId":"u2"},
    "cb646da71e854c96b63f798c55577906":{
      "scriptId":"u3"},
    "b8cdef99dcbe4896abedb18c3f345c90":{
      "scriptId":"u4"},
    "a32c1b5dcaf0468983d6166dad3ea824":{
      "scriptId":"u5"},
    "01c721bc7a3d47ccae230da6e2d65ff7":{
      "scriptId":"u6"},
    "3514d87df0c049ee9c849280663345d9":{
      "scriptId":"u7"},
    "3466a1cd175f430584553c10b1edf33d":{
      "scriptId":"u8"},
    "cd0a516c71eb4d2c8e672d05c642c991":{
      "scriptId":"u9"},
    "85a8f99d46d14886a1905f04baf566fb":{
      "scriptId":"u10"},
    "04bf35a54e144fcb934a4e5a73e39244":{
      "scriptId":"u11"},
    "69cb02fc45f34f3b9f017d05a29b8c4f":{
      "scriptId":"u12"},
    "2a33eaeb54fa445bac7c2f62ec8e3a21":{
      "scriptId":"u13"},
    "86333555d6344830aa2b49af1e567d03":{
      "scriptId":"u14"},
    "289a59966198463c899b1f05f5bb3703":{
      "scriptId":"u15"},
    "52b05746b2b9403385f0ef563e03a2d7":{
      "scriptId":"u16"},
    "5f81604a2ed04c1aabed183e7754aa82":{
      "scriptId":"u17"},
    "983d5598f59344a09d3542132e03411c":{
      "scriptId":"u18"},
    "2bab2ee702594c528b678535675229db":{
      "scriptId":"u19"}}});